#![forbid(unsafe_code)]

pub(super) fn house_source_label_aliases(canonical_name: &str) -> &'static [&'static str] {
    match canonical_name {
        "Placidus" => &["Placidus house system", "Placidus table of houses"],
        "Koch" => &[
            "Koch houses",
            "Koch house system",
            "house system of the birth place",
            "Koch table of houses",
            "W. Koch",
            "W Koch",
        ],
        "Porphyry" => &[
            "Equal Quadrant",
            "Porphyry house system",
            "Porphyry table of houses",
        ],
        "Regiomontanus" => &[
            "Regiomontanus houses",
            "Regiomontanus house system",
            "Regiomontanus table of houses",
        ],
        "Campanus" => &[
            "Campanus houses",
            "Campanus house system",
            "Campanus table of houses",
        ],
        "Equal" => &[
            "A equal",
            "E equal = A",
            "Equal houses",
            "Equal house system",
            "Equal House",
            "Equal table of houses",
            "Wang",
            "Equal (cusp 1 = Asc)",
        ],
        "Whole Sign" => &[
            "W equal, whole sign",
            "Whole Sign houses",
            "Whole Sign table of houses",
            "Whole-sign",
            "Whole Sign system",
            "Whole Sign house system",
        ],
        "Alcabitius" => &[
            "Alcabitius houses",
            "Alcabitius house system",
            "Alcabitius table of houses",
        ],
        "Meridian" => &[
            "X",
            "Meridian houses",
            "Meridian table of houses",
            "Meridian house system",
            "ARMC",
            "Axial Rotation",
            "Axial rotation system",
            "Zariel",
            "X axial rotation system/ Meridian houses",
        ],
        "Axial" => &["Axial variants", "A"],
        "Topocentric" => &[
            "T",
            "Polich-Page",
            "Polich/Page",
            "Polich Page",
            "Polich-Page \"topocentric\" table of houses",
            "T Polich/Page (\"topocentric\")",
            "T topocentric",
            "Topocentric house system",
            "Topocentric table of houses",
        ],
        "Morinus" => &["M", "Morinus houses", "Morinus house system"],
        "Equal (MC)" => &[
            "D equal / MC",
            "Equal from MC",
            "Equal (from MC)",
            "Equal (from MC) table of houses",
            "Equal (MC) table of houses",
            "Equal/MC table of houses",
            "Equal (MC) house system",
            "Equal/MC house system",
            "Equal MC",
            "Equal/MC",
            "Equal Midheaven",
            "Equal Midheaven house system",
            "Equal Midheaven table of houses",
            "Equal/MC = 10th",
        ],
        "Equal (1=Aries)" => &[
            "N",
            "N whole sign houses, 1. house = Aries",
            "Equal/1=Aries",
            "Equal Aries",
            "Aries houses",
            "Whole Sign (house 1 = Aries)",
            "Whole Sign (house 1 = Aries) table of houses",
            "Equal (1=Aries) table of houses",
            "Equal/1=Aries table of houses",
            "Equal (1=Aries) house system",
            "Equal/1=Aries house system",
            "Whole sign houses, 1. house = Aries",
            "Equal/1=0 Aries",
            "Equal (cusp 1 = 0° Aries)",
        ],
        "Vehlow Equal" => &[
            "V equal Vehlow",
            "Vehlow-equal table of houses",
            "Vehlow Equal table of houses",
            "Vehlow-equal",
            "Vehlow",
        ],
        "Sripati" => &[
            "S",
            "S sripati",
            "Śrīpati",
            "Sripati house system",
            "Sripati table of houses",
        ],
        "Carter (poli-equatorial)" => &[
            "Carter",
            "Carter's poli-equatorial",
            "Carter's poli-equatorial table of houses",
            "Poli-Equatorial",
            "Poli-equatorial",
        ],
        "Horizon/Azimuth" => &[
            "Horizon/Azimuth",
            "Horizon",
            "Azimuth",
            "Horizontal",
            "Azimuthal",
            "Horizon table of houses",
            "Horizontal table of houses",
            "Azimuthal table of houses",
            "Horizon/Azimuth table of houses",
            "Horizon house system",
            "Horizon/Azimuth house system",
            "Horizontal house system",
            "Azimuth house system",
            "Azimuthal house system",
            "horizon/azimut",
            "horizon/azimuth",
        ],
        "APC" => &[
            "Y",
            "APC",
            "Ram school",
            "Ram's school",
            "Ramschool",
            "WvA",
            "Y APC houses",
            "APC houses",
            "APC, also known as \u{201c}Ram school\u{201d}, table of houses",
            "APC house system",
            "Ascendant Parallel Circle",
        ],
        "Krusinski-Pisa-Goelzer" => &[
            "U",
            "Krusinski",
            "Krusinski-Pisa",
            "Krusinski Pisa",
            "Krusinski/Pisa/Goelzer",
            "Krusinski-Pisa-Goelzer table of houses",
            "U krusinski-pisa-goelzer",
            "Krusinski/Pisa/Goelzer house system",
            "Pisa-Goelzer",
        ],
        "Albategnius" => &[
            "Albategnius table of houses",
            "Savard-A",
            "Savard A",
            "Savard's Albategnius",
        ],
        "Pullen SD" => &[
            "Pullen SD table of houses",
            "Pullen SD (Neo-Porphyry) table of houses",
            "Pullen SD (Neo-Porphyry)",
            "Neo-Porphyry",
            "Pullen (Sinusoidal Delta)",
            "Pullen SD (Sinusoidal Delta)",
            "Pullen SD (Sinusoidal Delta) table of houses",
            "Pullen sinusoidal delta",
        ],
        "Pullen SR" => &[
            "Pullen SR table of houses",
            "Pullen SR (Sinusoidal Ratio) table of houses",
            "Pullen SR (Sinusoidal Ratio)",
            "Pullen (Sinusoidal Ratio)",
            "Pullen sinusoidal ratio",
        ],
        "Sunshine" => &[
            "I",
            "I sunshine",
            "Sunshine",
            "Sunshine houses",
            "Sunshine house system",
            "Sunshine table of houses",
            "Sunshine table of houses, by Bob Makransky",
            "Makransky Sunshine",
            "Bob Makransky",
            "Treindl Sunshine",
        ],
        "Gauquelin sectors" => &[
            "G",
            "Gauquelin",
            "Gauquelin sector",
            "Gauquelin sectors",
            "Gauquelin table of sectors",
        ],
        _ => &[],
    }
}

pub(super) fn ayanamsa_source_label_aliases(canonical_name: &str) -> &'static [&'static str] {
    match canonical_name {
        "PVR Pushya-paksha" => &[
            "True Pushya (PVRN Rao)",
            "Pushya-paksha",
            "Pushya Paksha",
            "PVR Pushya Paksha",
            "PVR",
            "P.V.R. Narasimha Rao",
        ],
        "Raman" => &[
            "B. V. Raman",
            "B.V. Raman",
            "B V Raman",
            "Raman Ayanamsha",
            "Raman ayanamsa",
        ],
        "Krishnamurti" => &[
            "Krishnamurti Ayanamsha",
            "Krishnamurti Ayanamsa",
            "Krishnamurti ayanamsa",
            "Krishnamurti (Swiss)",
            "Krishnamurti Paddhati",
            "KP ayanamsa",
        ],
        "Fagan/Bradley" => &[
            "Fagan/Bradley Ayanamsha",
            "Fagan/Bradley",
            "Fagan Bradley",
            "Fagan / Bradley",
            "Fagan-Bradley",
        ],
        "Lahiri" => &[
            "Chitra Paksha",
            "Chitrapaksha",
            "Chitra-paksha",
            "Lahiri Ayanamsha",
            "Lahiri ayanamsa",
        ],
        "True Pushya" => &["True Pushya ayanamsa", "Pushya"],
        "True Chitra" => &["Chitra", "True Chitra ayanamsa"],
        "True Citra" => &[
            "True Citra ayanamsa",
            "True Citra Paksha",
            "True Chitra Paksha",
            "True Chitrapaksha",
        ],
        "True Revati" => &["True Revati ayanamsa"],
        "True Mula" => &[
            "True Mula (Chandra Hari)",
            "True Mula ayanamsa",
            "Chandra Hari",
        ],
        "Udayagiri" => &["Udayagiri ayanamsa"],
        "Usha Shashi" => &[
            "Usha Shashi",
            "Ushashashi",
            "Usha-Shashi",
            "Usha/Shashi",
            "Usha / Shashi",
            "Usha Shashi ayanamsa",
            "Revati",
        ],
        "Lahiri (ICRC)" => &["ICRC Lahiri", "Lahiri ICRC"],
        "Lahiri (1940)" => &["Lahiri original", "Panchanga Darpan Lahiri"],
        "DeLuce" => &["De Luce", "DeLuce ayanamsa"],
        "Yukteshwar" => &[
            "Yukteswar",
            "Sri Yukteswar",
            "Sri Yukteshwar",
            "Shri Yukteswar",
            "Shri Yukteshwar",
            "Yukteshwar ayanamsa",
        ],
        "J2000" => &["J2000.0"],
        "J1900" => &["J1900.0"],
        "B1950" => &["B1950.0"],
        "Sheoran" => &[
            "Sunil Sheoran",
            "Vedic Sheoran",
            "Vedic / Sheoran",
            "Sheoran ayanamsa",
            "Sheoran true",
            "True Sheoran ayanamsa",
            "\"Vedic\"/Sheoran",
        ],
        "Djwhal Khul" => &["Djwhal", "Djwhal Khul ayanamsa"],
        "JN Bhasin" => &["J. N. Bhasin", "J.N. Bhasin", "Bhasin"],
        "Suryasiddhanta (Mean Sun)" => &[
            "Suryasiddhanta, mean Sun",
            "Surya Siddhanta, mean Sun",
            "Suryasiddhanta mean sun",
            "Surya Siddhanta mean sun",
            "Suryasiddhanta MSUN",
            "Surya Siddhanta MSUN",
        ],
        "Suryasiddhanta (499 CE)" => &[
            "Suryasiddhanta",
            "Surya Siddhanta",
            "Suryasiddhanta 499",
            "Surya Siddhanta 499",
            "Suryasiddhanta 499 CE",
            "Surya Siddhanta 499 CE",
        ],
        "Aryabhata (499 CE)" => &[
            "Aryabhata",
            "Aryabhata 499",
            "Aryabhata 499 CE",
            "Aryabhatan Kaliyuga",
            "Aryabhata Kaliyuga",
        ],
        "Aryabhata (Mean Sun)" => &[
            "Aryabhata, mean Sun",
            "Aryabhata mean sun",
            "Aryabhata MSUN",
        ],
        "Aryabhata (522 CE)" => &["Aryabhata 522", "Aryabhata 522 CE"],
        "Babylonian (Kugler 1)" => &["Babylonian/Kugler 1", "Babylonian Kugler 1", "Babylonian 1"],
        "Babylonian (Kugler 2)" => &["Babylonian/Kugler 2", "Babylonian Kugler 2", "Babylonian 2"],
        "Babylonian (Kugler 3)" => &["Babylonian/Kugler 3", "Babylonian Kugler 3", "Babylonian 3"],
        "Babylonian (Britton)" => &["Babylonian/Britton", "Babylonian Britton"],
        "Babylonian (Huber)" => &["Babylonian/Huber", "Babylonian Huber"],
        "Babylonian (Eta Piscium)" => &["Babylonian/Eta Piscium"],
        "Babylonian (Aldebaran)" => &["Babylonian/Aldebaran = 15 Tau"],
        "Lahiri (VP285)" => &["Lahiri VP285", "VP285"],
        "Krishnamurti (VP291)" => &[
            "KP VP291",
            "Krishnamurti VP291",
            "Krishnamurti-Senthilathiban",
            "VP291",
        ],
        "True Sheoran" => &["Sheoran true", "True Sheoran ayanamsa"],
        "Galactic Center (Rgilbrand)" => &[
            "Galactic Center (Gil Brand)",
            "Gil Brand",
            "Rgilbrand",
            "Galactic center Rgilbrand",
        ],
        "Galactic Center (Mardyks)" => &[
            "Skydram",
            "Skydram/Galactic Alignment",
            "Skydram (Mardyks)",
            "Mardyks",
            "Galactic center Mardyks",
        ],
        "Galactic Center (Mula/Wilhelm)" => &[
            "Dhruva/Gal.Center/Mula (Wilhelm)",
            "Mula Wilhelm",
            "Wilhelm",
            "Galactic center Mula/Wilhelm",
        ],
        "Galactic Center (Cochrane)" => &[
            "Cochrane (Gal.Center = 0 Cap)",
            "Gal. Center = 0 Cap",
            "Cochrane",
            "Galactic center Cochrane",
            "David Cochrane",
        ],
        "Galactic Center" => &["Galact. Center = 0 Sag", "Gal. Center = 0 Sag"],
        "Sassanian" => &["Zij al-Shah", "Sasanian"],
        "Galactic Equator (IAU 1958)" => &[
            "Galactic Equator (IAU1958)",
            "IAU 1958",
            "Galactic equator IAU 1958",
        ],
        "Galactic Equator (True)" => &["True galactic equator", "Galactic equator true"],
        "Galactic Equator (Mula)" => &[
            "Galactic Equator mid-Mula",
            "Mula galactic equator",
            "Galactic equator Mula",
        ],
        "Galactic Equator" => &["Galactic equator", "Gal. Eq."],
        "Galactic Equator (Fiorenza)" => &[
            "Fiorenza",
            "Galactic equator Fiorenza",
            "Nick Anthony Fiorenza",
        ],
        "Valens Moon" => &[
            "Vettius Valens",
            "Valens",
            "Moon",
            "Moon sign",
            "Moon sign ayanamsa",
            "Valens Moon ayanamsa",
        ],
        _ => &[],
    }
}
