#!/usr/bin/env bash
# Regenerate apparent-of-date goldens from JPL Horizons (quantity 31, ObsEcLon:
# apparent ecliptic longitude referred to the IAU76/80 ecliptic-of-date, with
# light-time, gravitational deflection, and stellar aberrations),
# geocentric observer (500@399). Run manually when refreshing the corpus.
#
# Tolerances: Sun ~5 arcsec (aberration applied once via apparent_sun_position; post-fix
# residual a few arcsec, was masked by ~20" double-count under old 26" tolerance); planets
# 26 arcsec (polynomial-fit ephemeris accuracy vs JPL DE441, apparent-mode residuals
# 15-25 arcsec); Moon 45 arcsec (ELP2000 theory limit, unchanged).
# 433-Eros is EXCLUDED: the light-time iteration diverges or goes out of range at most
# epochs because Eros's packaged data span is too narrow for apparent-mode convergence.
set -euo pipefail
OUT="$(dirname "$0")/../data/apparent-goldens.csv"
API="https://ssd.jpl.nasa.gov/api/horizons.api"
EPOCHS="2415025.5 2433282.5 2451545.0 2469807.5 2488065.5" # ~1900,1950,2000,2050,~2100 (JD)
# NOTE: 2415025.5 = 1900-Jan-06 (5 days past the packaged-backend start 2415020.5, to
# avoid apparent light-time iteration stepping before coverage); 2488065.5 = 2099-Dec-26
# (4 days before coverage end 2488069.5, same reason). Interior epochs 1950/2000/2050
# are well clear of the boundaries.
# body label -> Horizons COMMAND code (Eros excluded; see script header)
BODIES="Sun:10 Moon:301 Mercury:199 Venus:299 Mars:499 Jupiter:599 Saturn:699 Uranus:799 Neptune:899 Pluto:999"
{
  echo "# Source: JPL Horizons API ($API), EPHEM_TYPE=OBSERVER, CENTER='500@399',"
  echo "# QUANTITIES='31' (ObsEcLon, apparent ecliptic longitude referred to the IAU76/80 ecliptic-of-date,"
  echo "# with light-time, gravitational deflection, and stellar aberrations), ANG_FORMAT=DEG, extra_prec=YES."
  echo "# Regenerated by crates/pleiades-validate/scripts/regen-apparent-goldens.sh"
  echo "#"
  echo "# TOLERANCE RATIONALE (per-body model limits):"
  echo "#   - Sun: apparent corrections (precession, nutation, annual aberration) applied ONCE"
  echo "#     via apparent_sun_position; for the geocentric Sun light-time and annual aberration"
  echo "#     are the same effect, so no separate light-time re-query is performed. Residual vs"
  echo "#     Horizons Q31 is now a few arcsec (was masked by a ~20\" aberration double-count under"
  echo "#     the old 26\" tolerance). Tolerance = max observed residual + 2\"."
  echo "#   - Planets: polynomial-fit ephemeris matches JPL DE441 to ~0.01 deg (36 arcsec);"
  echo "#     apparent-mode residuals 15-25 arcsec, set to max observed residual + 2 arcsec margin."
  echo "#   - Moon: ELP2000-based theory; aberration formula is the planetary formula applied to a body"
  echo "#     sharing Earth's orbit, causing a systematic error. Max observed residual 44 arcsec; tolerance"
  echo "#     set to 45 arcsec."
  echo "#   - 433-Eros: EXCLUDED. The light-time iteration diverges or goes out of range at 4 of 5 epochs"
  echo "#     because Eros's packaged data covers a limited span and the apparent-mode iteration steps outside"
  echo "#     it. Apparent-mode validation of Eros is not supported with the current packaged backend."
  echo "#     (At J2000 the residual was 68 arcsec, also exceeding any reasonable tolerance.)"
  echo "#"
  echo "# EPOCHS: 2415025.5 = 1900-Jan-06 TT (5 days past coverage start to avoid light-time stepping"
  echo "# before data start); 2488065.5 = 2099-Dec-26 TT (4 days before coverage end for same reason)."
  echo "body,jd_tt,apparent_longitude_deg,tolerance_arcsec"
  for entry in $BODIES; do
    label="${entry%%:*}"; code="${entry##*:}"
    # Moon is theory-limited under the generic pipeline (annual aberration is
    # mis-applied to a body sharing Earth's velocity); give it a looser tolerance.
    if [ "$label" = "Moon" ]; then tol=45.0; else tol=26.0; fi
    for jd in $EPOCHS; do
      lon=$(curl -sS -m 30 "$API?format=text&COMMAND='$code'&EPHEM_TYPE=OBSERVER&CENTER='500@399'&TLIST='$jd'&QUANTITIES='31'&ANG_FORMAT=DEG&CAL_FORMAT=JD&extra_prec=YES" \
        | sed -n '/\$\$SOE/,/\$\$EOE/p' | sed '1d;$d' | awk '{print $2}')
      echo "$label,$jd,$lon,$tol"
    done
  done
} > "$OUT"
echo "wrote $OUT"
