#!/usr/bin/env bash
# Regenerate apparent equatorial (RA/Dec) of-date goldens from JPL Horizons
# (QUANTITIES='2': apparent RA & DEC, referred to the true equator and equinox
# of date, with light-time, deflection, and stellar aberration), geocentric
# observer (500@399). Same epochs/bodies as regen-apparent-goldens.sh. Run
# manually when refreshing the corpus.
#
# Tolerances (RA applies to the cos(Dec)-weighted residual, Dec to the signed residual):
#   Sun 6" (a floor; max observed cos(Dec)-weighted RA residual is 2.825" after #93),
#   per-body RA/Dec tolerances = max observed + 2" (#93, 2026-09-30). The Sun/inner-planet/
#   Moon residuals are dominated by the goldens' UT epoch tag (this script does not pass
#   TIME_TYPE=TT; FU-14 in docs/follow-ups.md). 433-Eros excluded (apparent iteration
#   diverges; see apparent gate header).
set -euo pipefail
OUT="$(dirname "$0")/../data/equatorial-goldens.csv"
API="https://ssd.jpl.nasa.gov/api/horizons.api"
EPOCHS="2415025.5 2433282.5 2451545.0 2469807.5 2488065.5"
BODIES="Sun:10 Moon:301 Mercury:199 Venus:299 Mars:499 Jupiter:599 Saturn:699 Uranus:799 Neptune:899 Pluto:999"
{
  echo "# Source: JPL Horizons API ($API), EPHEM_TYPE=OBSERVER, CENTER='500@399',"
  echo "# QUANTITIES='2' (apparent RA & DEC, true equator/equinox of date, with light-time,"
  echo "# deflection, and stellar aberration), ANG_FORMAT=DEG, extra_prec=YES."
  echo "# Regenerated by crates/pleiades-validate/scripts/regen-equatorial-goldens.sh"
  echo "#"
  echo "# TOLERANCE RATIONALE (per-body model limits, applied to cos(Dec)-weighted RA residual"
  echo "# and signed Dec residual):"
  echo "#   - Sun: The RA/Dec channel converts the apparent ecliptic longitude via obliquity"
  echo "#     rotation. Max observed RA residual (cos(Dec)-weighted) is 2.825\" after #93"
  echo "#     (2026-09-30), essentially the goldens' UT epoch tag (FU-14). The 6\" tolerance is"
  echo "#     kept as a floor, not max + margin."
  echo "#   - Planets: light-time re-query carries annual aberration, no separate term (#93,"
  echo "#     2026-09-30); the residual is dominated by the goldens' UT-tagged Horizons epochs"
  echo "#     (fetched without TIME_TYPE=TT; see FU-14), not the ephemeris fit. RA tolerance = per-body max"
  echo "#     observed cos(Dec)-weighted residual + 2\" (Mercury 4.533\", Venus 3.682\", Mars 1.890\","
  echo "#     Jupiter 0.453\", Saturn 0.258\", Uranus 0.253\", Neptune 0.180\", Pluto 0.172\"); Dec"
  echo "#     tolerance = per-body max observed + 2\" where that is below the former value."
  echo "#   - Moon: same path; RA max observed 38.283\" after #93 (2026-09-30), tolerance = max + 2\"."
  echo "#     Dec max observed 12.370\" (jd 2469807.5), tolerance 14.4\". The remaining residual is the"
  echo "#     same UT/TT tag; tracked as FU-14."
  echo "#   - 433-Eros: EXCLUDED. Light-time iteration diverges at most epochs; see apparent gate."
  echo "#"
  echo "# EPOCHS: 2415025.5 = 1900-Jan-06 TT; 2433282.5 = 1950 TT; 2451545.0 = J2000 TT;"
  echo "#         2469807.5 = 2050 TT; 2488065.5 = 2099-Dec-26 TT."
  echo "body,jd_tt,apparent_ra_deg,apparent_dec_deg,ra_tolerance_arcsec,dec_tolerance_arcsec"
  for entry in $BODIES; do
    label="${entry%%:*}"; code="${entry##*:}"
    # Per-body RA / Dec tolerance = max observed residual + 2" (measured 2026-09-30, #93).
    case "$label" in
      Sun) ra_tol=6.0; dec_tol=6.0 ;;
      Moon) ra_tol=40.3; dec_tol=14.4 ;;
      Mercury) ra_tol=6.6; dec_tol=2.5 ;;
      Venus) ra_tol=5.7; dec_tol=3.1 ;;
      Mars) ra_tol=3.9; dec_tol=2.8 ;;
      Jupiter) ra_tol=2.5; dec_tol=2.1 ;;
      Saturn) ra_tol=2.3; dec_tol=2.1 ;;
      Uranus) ra_tol=2.3; dec_tol=2.1 ;;
      Neptune) ra_tol=2.2; dec_tol=2.1 ;;
      Pluto) ra_tol=2.2; dec_tol=2.1 ;;
    esac
    for jd in $EPOCHS; do
      radec=$(curl -sS -m 30 "$API?format=text&COMMAND='$code'&EPHEM_TYPE=OBSERVER&CENTER='500@399'&TLIST='$jd'&QUANTITIES='2'&ANG_FORMAT=DEG&CAL_FORMAT=JD&extra_prec=YES" \
        | sed -n '/\$\$SOE/,/\$\$EOE/p' | sed '1d;$d' | awk '{print $2","$3}')
      echo "$label,$jd,$radec,$ra_tol,$dec_tol"
    done
  done
} > "$OUT"
echo "wrote $OUT"
