#!/usr/bin/env bash
# Regenerate apparent equatorial (RA/Dec) of-date goldens from JPL Horizons
# (QUANTITIES='2': apparent RA & DEC, referred to the true equator and equinox
# of date, with light-time, deflection, and stellar aberration), geocentric
# observer (500@399), epochs tagged TT (TIME_TYPE=TT). Same epochs/bodies as
# regen-apparent-goldens.sh. Run manually when refreshing the corpus.
#
# Tolerances (RA applies to the cos(Dec)-weighted residual, Dec to the signed residual):
#   per-body = max observed + 2", rounded up to 0.1" (FU-14, 2026-09-30): RA 2.2" for every
#   body except Uranus (2.3"); Dec 2.1" for every body except Venus (2.2"). Measured maxima
#   are 0.10"-0.25" (RA) and 0.005"-0.18" (Dec), the packaged-ephemeris fit floor. Before
#   FU-14 the goldens were fetched without TIME_TYPE=TT (Horizons read TLIST as UT), which
#   is what the former 40.3"/14.4" Moon tolerances and the 6" Sun floor absorbed.
#   433-Eros excluded (apparent iteration diverges; see apparent gate header).
set -euo pipefail
OUT="$(dirname "$0")/../data/equatorial-goldens.csv"
API="https://ssd.jpl.nasa.gov/api/horizons.api"
EPOCHS="2415025.5 2433282.5 2451545.0 2469807.5 2488065.5"
BODIES="Sun:10 Moon:301 Mercury:199 Venus:299 Mars:499 Jupiter:599 Saturn:699 Uranus:799 Neptune:899 Pluto:999"

# Fetch one Horizons row for COMMAND=$1 at TLIST=$2 (JD, TT) with QUANTITIES=$3, and
# print the $$SOE..$$EOE data line. TIME_TYPE=TT makes Horizons read TLIST as TT, which
# is how the gate evaluates the row (jd_tt). Without it Horizons reads TLIST as UT and
# the goldens carry a dT-sized offset (about 38" for the Moon at 2050; FU-14). The
# header check refuses to write UT-tagged goldens if that ever regresses.
fetch_tt() {
  local text
  text=$(curl -sS -m 30 "$API?format=text&COMMAND='$1'&EPHEM_TYPE=OBSERVER&CENTER='500@399'&TLIST='$2'&TIME_TYPE=TT&QUANTITIES='$3'&ANG_FORMAT=DEG&CAL_FORMAT=JD&extra_prec=YES")
  if ! grep -q 'Date_________JDTT' <<<"$text"; then
    echo "Horizons did not tag COMMAND=$1 TLIST=$2 as TT (no Date_________JDTT header); refusing to write UT-tagged goldens" >&2
    return 1
  fi
  sed -n '/\$\$SOE/,/\$\$EOE/p' <<<"$text" | sed '1d;$d'
}
{
  echo "# Source: JPL Horizons API ($API), EPHEM_TYPE=OBSERVER, CENTER='500@399', TIME_TYPE=TT,"
  echo "# QUANTITIES='2' (apparent RA & DEC, true equator/equinox of date, with light-time,"
  echo "# deflection, and stellar aberration), ANG_FORMAT=DEG, extra_prec=YES."
  echo "# Regenerated by crates/pleiades-validate/scripts/regen-equatorial-goldens.sh"
  echo "#"
  echo "# TOLERANCE RATIONALE (per-body model limits, applied to cos(Dec)-weighted RA residual"
  echo "# and signed Dec residual):"
  echo "#   - Epoch tag: TLIST is passed with TIME_TYPE=TT, so Horizons evaluates each row at the"
  echo "#     same TT instant the gate uses (jd_tt). Goldens fetched before FU-14 (2026-09-30) lacked"
  echo "#     the tag, Horizons read them as UT, and every row carried a dT-sized offset (about 38\""
  echo "#     in RA for the Moon at 2050). Those offsets were what the former 40.3\"/14.4\" Moon"
  echo "#     tolerances and the 6\" Sun floor absorbed."
  echo "#   - The RA/Dec channel converts the apparent ecliptic position via obliquity rotation;"
  echo "#     the Sun applies its apparent corrections once (apparent_sun_position), the planets"
  echo "#     and Moon carry annual aberration in the light-time re-query with no separate term"
  echo "#     (#93, 2026-09-30)."
  echo "#   - Tolerance = per-body max observed + 2\", rounded up to 0.1\". Maxima measured 2026-09-30"
  echo "#     against TT-tagged goldens. RA (cos(Dec)-weighted): Sun 0.111\", Moon 0.102\","
  echo "#     Mercury 0.114\", Venus 0.104\", Mars 0.170\", Jupiter 0.114\", Saturn 0.128\","
  echo "#     Uranus 0.249\", Neptune 0.167\", Pluto 0.160\". Dec: Sun 0.005\", Moon 0.046\","
  echo "#     Mercury 0.014\", Venus 0.180\", Mars 0.043\", Jupiter 0.037\", Saturn 0.035\","
  echo "#     Uranus 0.088\", Neptune 0.066\", Pluto 0.084\" (the packaged-ephemeris fit floor)."
  echo "#   - 433-Eros: EXCLUDED. Light-time iteration diverges at most epochs; see apparent gate."
  echo "#"
  echo "# EPOCHS: 2415025.5 = 1900-Jan-06 TT; 2433282.5 = 1950 TT; 2451545.0 = J2000 TT;"
  echo "#         2469807.5 = 2050 TT; 2488065.5 = 2099-Dec-26 TT."
  echo "body,jd_tt,apparent_ra_deg,apparent_dec_deg,ra_tolerance_arcsec,dec_tolerance_arcsec"
  for entry in $BODIES; do
    label="${entry%%:*}"; code="${entry##*:}"
    # Per-body RA / Dec tolerance = max observed residual + 2", rounded up to 0.1" (measured 2026-09-30, FU-14).
    case "$label" in
      Sun) ra_tol=2.2; dec_tol=2.1 ;;
      Moon) ra_tol=2.2; dec_tol=2.1 ;;
      Mercury) ra_tol=2.2; dec_tol=2.1 ;;
      Venus) ra_tol=2.2; dec_tol=2.2 ;;
      Mars) ra_tol=2.2; dec_tol=2.1 ;;
      Jupiter) ra_tol=2.2; dec_tol=2.1 ;;
      Saturn) ra_tol=2.2; dec_tol=2.1 ;;
      Uranus) ra_tol=2.3; dec_tol=2.1 ;;
      Neptune) ra_tol=2.2; dec_tol=2.1 ;;
      Pluto) ra_tol=2.2; dec_tol=2.1 ;;
    esac
    for jd in $EPOCHS; do
      radec=$(fetch_tt "$code" "$jd" 2 | awk '{print $2","$3}')
      echo "$label,$jd,$radec,$ra_tol,$dec_tol"
    done
  done
} > "$OUT.tmp"
mv "$OUT.tmp" "$OUT"
echo "wrote $OUT"
