#!/usr/bin/env bash
# Regenerate apparent-of-date goldens from JPL Horizons (quantity 31, ObsEcLon:
# apparent ecliptic longitude referred to the IAU76/80 ecliptic-of-date, with
# light-time, gravitational deflection, and stellar aberrations),
# geocentric observer (500@399). Run manually when refreshing the corpus.
#
# Tolerances: Sun ~5 arcsec (aberration applied once via apparent_sun_position; post-fix
# residual a few arcsec, was masked by ~20" double-count under old 26" tolerance); planets
# 26 arcsec (polynomial-fit ephemeris accuracy vs JPL DE441, apparent-mode residuals
# 15-25 arcsec); Moon 45 arcsec (ELP2000 theory limit, unchanged).
# 433-Eros is EXCLUDED: the light-time iteration diverges or goes out of range at most
# epochs because Eros's packaged data span is too narrow for apparent-mode convergence.
set -euo pipefail
OUT="$(dirname "$0")/../data/apparent-goldens.csv"
API="https://ssd.jpl.nasa.gov/api/horizons.api"
EPOCHS="2415025.5 2433282.5 2451545.0 2469807.5 2488065.5" # ~1900,1950,2000,2050,~2100 (JD)
# NOTE: 2415025.5 = 1900-Jan-06 (5 days past the packaged-backend start 2415020.5, to
# avoid apparent light-time iteration stepping before coverage); 2488065.5 = 2099-Dec-26
# (4 days before coverage end 2488069.5, same reason). Interior epochs 1950/2000/2050
# are well clear of the boundaries.
# body label -> Horizons COMMAND code (Eros excluded; see script header)
BODIES="Sun:10 Moon:301 Mercury:199 Venus:299 Mars:499 Jupiter:599 Saturn:699 Uranus:799 Neptune:899 Pluto:999"
{
  echo "# Source: JPL Horizons API ($API), EPHEM_TYPE=OBSERVER, CENTER='500@399',"
  echo "# QUANTITIES='31' (ObsEcLon, apparent ecliptic longitude referred to the IAU76/80 ecliptic-of-date,"
  echo "# with light-time, gravitational deflection, and stellar aberrations), ANG_FORMAT=DEG, extra_prec=YES."
  echo "# Regenerated by crates/pleiades-validate/scripts/regen-apparent-goldens.sh"
  echo "#"
  echo "# TOLERANCE RATIONALE (per-body model limits):"
  echo "#   - Sun: apparent corrections (precession, nutation, annual aberration) applied ONCE"
  echo "#     via apparent_sun_position; for the geocentric Sun light-time and annual aberration"
  echo "#     are the same effect, so no separate light-time re-query is performed. Residual vs"
  echo "#     Horizons Q31 is now a few arcsec (was masked by a ~20\" aberration double-count under"
  echo "#     the old 26\" tolerance). Tolerance = max observed residual + 2\"."
  echo "#   - Planets: the light-time re-query of the geocentric position carries annual"
  echo "#     aberration; no separate term is added (#93, 2026-09-30). The residual is the"
  echo "#     polynomial-fit ephemeris vs DE441 floor. Tolerance = per-body max observed"
  echo "#     residual + 2\" (Mercury 4.541\", Venus 3.670\", Mars 2.028\", Jupiter 0.464\","
  echo "#     Saturn 0.261\", Uranus 0.256\", Neptune 0.189\", Pluto 0.183\"), measured 2026-09-30."
  echo "#     The former 26\" ceiling was absorbing a ~20\" double count."
  echo "#   - Moon: same path. Max observed residual 38.781\" (2026-09-30) after the #93 fix;"
  echo "#     tolerance = max + 2\". The remaining residual is tracked as FU-14 in"
  echo "#     docs/follow-ups.md."
  echo "#   - 433-Eros: EXCLUDED. The light-time iteration diverges or goes out of range at 4 of 5 epochs"
  echo "#     because Eros's packaged data covers a limited span and the apparent-mode iteration steps outside"
  echo "#     it. Apparent-mode validation of Eros is not supported with the current packaged backend."
  echo "#     (At J2000 the residual was 68 arcsec, also exceeding any reasonable tolerance.)"
  echo "#"
  echo "# EPOCHS: 2415025.5 = 1900-Jan-06 TT (5 days past coverage start to avoid light-time stepping"
  echo "# before data start); 2488065.5 = 2099-Dec-26 TT (4 days before coverage end for same reason)."
  echo "body,jd_tt,apparent_longitude_deg,tolerance_arcsec"
  for entry in $BODIES; do
    label="${entry%%:*}"; code="${entry##*:}"
    # Per-body tolerance = max observed residual + 2" (measured 2026-09-30, #93).
    case "$label" in
      Sun) tol=5.0 ;;
      Moon) tol=40.8 ;;
      Mercury) tol=6.6 ;;
      Venus) tol=5.7 ;;
      Mars) tol=4.1 ;;
      Jupiter) tol=2.5 ;;
      Saturn) tol=2.3 ;;
      Uranus) tol=2.3 ;;
      Neptune) tol=2.2 ;;
      Pluto) tol=2.2 ;;
    esac
    for jd in $EPOCHS; do
      lon=$(curl -sS -m 30 "$API?format=text&COMMAND='$code'&EPHEM_TYPE=OBSERVER&CENTER='500@399'&TLIST='$jd'&QUANTITIES='31'&ANG_FORMAT=DEG&CAL_FORMAT=JD&extra_prec=YES" \
        | sed -n '/\$\$SOE/,/\$\$EOE/p' | sed '1d;$d' | awk '{print $2}')
      echo "$label,$jd,$lon,$tol"
    done
  done
} > "$OUT"
echo "wrote $OUT"
