#!/usr/bin/env bash
# Regenerate apparent equatorial (RA/Dec) of-date goldens from JPL Horizons
# (QUANTITIES='2': apparent RA & DEC, referred to the true equator and equinox
# of date, with light-time, deflection, and stellar aberration), geocentric
# observer (500@399). Same epochs/bodies as regen-apparent-goldens.sh. Run
# manually when refreshing the corpus.
#
# Tolerances (applied to BOTH cos(Dec)-weighted RA residual and signed Dec residual):
#   Sun 6" (ecliptic gate is 5"; RA/Dec adds a small obliquity-rotation epsilon above
#   that floor; max observed cos(Dec)-weighted RA residual ~5.06" at 1900),
#   planets 26", Moon 45". 433-Eros excluded (apparent iteration diverges; see
#   apparent gate header).
set -euo pipefail
OUT="$(dirname "$0")/../data/equatorial-goldens.csv"
API="https://ssd.jpl.nasa.gov/api/horizons.api"
EPOCHS="2415025.5 2433282.5 2451545.0 2469807.5 2488065.5"
BODIES="Sun:10 Moon:301 Mercury:199 Venus:299 Mars:499 Jupiter:599 Saturn:699 Uranus:799 Neptune:899 Pluto:999"
{
  echo "# Source: JPL Horizons API ($API), EPHEM_TYPE=OBSERVER, CENTER='500@399',"
  echo "# QUANTITIES='2' (apparent RA & DEC, true equator/equinox of date, with light-time,"
  echo "# deflection, and stellar aberration), ANG_FORMAT=DEG, extra_prec=YES."
  echo "# Regenerated by crates/pleiades-validate/scripts/regen-equatorial-goldens.sh"
  echo "#"
  echo "# TOLERANCE RATIONALE (per-body model limits, applied to cos(Dec)-weighted RA residual"
  echo "# and signed Dec residual):"
  echo "#   - Sun: The RA/Dec channel converts the apparent ecliptic longitude via obliquity"
  echo "#     rotation, adding a small epsilon above the ecliptic-gate's 5\" floor. Max observed"
  echo "#     RA residual (cos(Dec)-weighted) is ~5.06\" at the 1900 epoch — the farthest from"
  echo "#     J2000 in the corpus. Tolerance set to 6\" (max + ~1\" margin)."
  echo "#   - Planets: polynomial-fit ephemeris accuracy vs JPL DE441, apparent-mode residuals"
  echo "#     15-25 arcsec; tolerance 26\" matches the ecliptic apparent gate."
  echo "#   - Moon: ELP2000 theory limit (annual aberration systematic), tolerance 45\" unchanged."
  echo "#   - 433-Eros: EXCLUDED. Light-time iteration diverges at most epochs; see apparent gate."
  echo "#"
  echo "# EPOCHS: 2415025.5 = 1900-Jan-06 TT; 2433282.5 = 1950 TT; 2451545.0 = J2000 TT;"
  echo "#         2469807.5 = 2050 TT; 2488065.5 = 2099-Dec-26 TT."
  echo "body,jd_tt,apparent_ra_deg,apparent_dec_deg,ra_tolerance_arcsec,dec_tolerance_arcsec"
  for entry in $BODIES; do
    label="${entry%%:*}"; code="${entry##*:}"
    if [ "$label" = "Moon" ]; then tol=45.0; elif [ "$label" = "Sun" ]; then tol=6.0; else tol=26.0; fi
    for jd in $EPOCHS; do
      radec=$(curl -sS -m 30 "$API?format=text&COMMAND='$code'&EPHEM_TYPE=OBSERVER&CENTER='500@399'&TLIST='$jd'&QUANTITIES='2'&ANG_FORMAT=DEG&CAL_FORMAT=JD&extra_prec=YES" \
        | sed -n '/\$\$SOE/,/\$\$EOE/p' | sed '1d;$d' | awk '{print $2","$3}')
      echo "$label,$jd,$radec,$tol,$tol"
    done
  done
} > "$OUT"
echo "wrote $OUT"
