//! Raw ayanamsa catalog tables — kept whole to preserve round-trip fidelity.

use pleiades_types::{Angle, Ayanamsa, JulianDay};

use crate::model::AyanamsaDescriptor;

pub(crate) const BASELINE_AYANAMSAS: &[AyanamsaDescriptor] = &[
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::Lahiri,
        "Lahiri",
        &[
            "Chitra Paksha",
            "Chitrapaksha",
            "Chitra-paksha",
            "Lahiri Ayanamsha",
            "Lahiri ayanamsa",
        ],
        "Default Indian sidereal standard in many astrology workflows.",
        Some(JulianDay::from_days(2_435_553.5)),
        Some(Angle::from_degrees(23.245_524_743)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::Raman,
        "Raman",
        &[
            "B. V. Raman",
            "B.V. Raman",
            "B V Raman",
            "Raman Ayanamsha",
            "Raman ayanamsa",
        ],
        "Popular named sidereal offset used in classical astrology software.",
        Some(JulianDay::from_days(2_415_020.0)),
        Some(Angle::from_degrees(21.014_44)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::Krishnamurti,
        "Krishnamurti",
        &[
            "KP",
            "Krishnamurti Ayanamsha",
            "Krishnamurti Ayanamsa",
            "Krishnamurti ayanamsa",
            "Krishnamurti (Swiss)",
            "Krishnamurti Paddhati",
            "KP ayanamsa",
        ],
        "Krishnamurti Paddhati ayanamsa.",
        Some(JulianDay::from_days(2_415_020.0)),
        Some(Angle::from_degrees(22.363_889)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::FaganBradley,
        "Fagan/Bradley",
        &["Fagan/Bradley Ayanamsha", "Fagan Bradley", "Fagan-Bradley"],
        "Western sidereal reference used by several astrology packages.",
        Some(JulianDay::from_days(2_433_282.423_46)),
        Some(Angle::from_degrees(24.042_044_444)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::TrueChitra,
        "True Chitra",
        &["Chitra", "True Chitra ayanamsa"],
        "True Chitra / Chitra-based sidereal variant.",
        Some(JulianDay::from_days(2_435_553.5)),
        Some(Angle::from_degrees(23.245_524_743)),
    ),
];

pub(crate) const RELEASE_AYANAMSAS: &[AyanamsaDescriptor] = &[
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::TrueCitra,
        "True Citra",
        &["True Citra ayanamsa"],
        "True Citra sidereal mode with the published zero point used by Swiss Ephemeris-style interoperability tables.",
        Some(JulianDay::from_days(1_825_182.872_330)),
        Some(Angle::from_degrees(50.256_748_3)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::J2000,
        "J2000",
        &["J2000.0"],
        "Swiss Ephemeris J2000 sidereal frame anchored to the standard J2000.0 epoch.",
        Some(JulianDay::from_days(2_451_545.0)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::J1900,
        "J1900",
        &["J1900.0"],
        "Swiss Ephemeris J1900 sidereal frame anchored to the standard J1900.0 epoch.",
        Some(JulianDay::from_days(2_415_020.0)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::B1950,
        "B1950",
        &["B1950.0"],
        "Swiss Ephemeris B1950 sidereal frame anchored to the FK4 B1950.0 epoch.",
        Some(JulianDay::from_days(2_433_282.423_459_05)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::TrueRevati,
        "True Revati",
        &["True Revati ayanamsa"],
        "True-nakshatra mode with the Revati reference point fixed to the Swiss Ephemeris zero date.",
        Some(JulianDay::from_days(1_926_902.658_267)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::TrueMula,
        "True Mula",
        &["True Mula (Chandra Hari)", "True Mula ayanamsa", "Chandra Hari"],
        "True-nakshatra mode with the Mula reference point fixed to the Swiss Ephemeris zero date.",
        Some(JulianDay::from_days(1_805_889.671_313)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::SuryasiddhantaRevati,
        "Suryasiddhanta (Revati)",
        &["SS Revati", "Suryasiddhanta Revati", "Surya Siddhanta Revati"],
        "Swiss Ephemeris SS Revati mode, anchored to the published Revati zero point used by the Surya Siddhanta family.",
        Some(JulianDay::from_days(1_903_396.8128654)),
        Some(Angle::from_degrees(-0.79167046)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::SuryasiddhantaCitra,
        "Suryasiddhanta (Citra)",
        &["SS Citra", "Suryasiddhanta Citra", "Surya Siddhanta Citra"],
        "Swiss Ephemeris SS Citra mode, anchored to the published Citra zero point used by the Surya Siddhanta family.",
        Some(JulianDay::from_days(1_903_396.8128654)),
        Some(Angle::from_degrees(2.11070444)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::LahiriIcrc,
        "Lahiri (ICRC)",
        &["ICRC Lahiri", "Lahiri ICRC"],
        "The 1956 Indian Calendar Reform Committee standard with a round 23°15′ reference value.",
        Some(JulianDay::from_days(2_435_553.5)),
        Some(Angle::from_degrees(23.25 - 0.00464207)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::Lahiri1940,
        "Lahiri (1940)",
        &["Lahiri original", "Panchanga Darpan Lahiri"],
        "Lahiri's earlier zero-date variant published in Panchanga Darpan.",
        Some(JulianDay::from_days(2_415_020.0)),
        Some(Angle::from_degrees(22.44597222)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::UshaShashi,
        "Usha Shashi",
        &["Ushashashi", "Usha-Shashi", "Usha/Shashi", "Usha / Shashi", "Usha Shashi ayanamsa", "Revati"],
        "Revati-bound zero-point variant used in the Greek-Arabic-Hindu tradition.",
        Some(JulianDay::from_days(2_415_020.0)),
        Some(Angle::from_degrees(360.0 - 341.33904)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::Suryasiddhanta499,
        "Suryasiddhanta (499 CE)",
        &["Suryasiddhanta 499", "Surya Siddhanta 499", "Suryasiddhanta 499 CE", "Surya Siddhanta 499 CE", "Surya Siddhanta", "Suryasiddhanta"],
        "Suryasiddhanta zero-point variant anchored to the 499 CE equinox.",
        Some(JulianDay::from_days(1_903_396.8128654)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::Aryabhata499,
        "Aryabhata (499 CE)",
        &[
            "Aryabhata 499",
            "Aryabhata 499 CE",
            "Aryabhata",
            "Aryabhatan Kaliyuga",
            "Aryabhata Kaliyuga",
        ],
        "Aryabhata zero-point variant anchored to the 499 CE dawn tradition.",
        Some(JulianDay::from_days(1_903_396.7895321)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::Sassanian,
        "Sassanian",
        &["Zij al-Shah", "Sasanian"],
        "Sassanian zero-point variant anchored to the 564 CE table-reform epoch.",
        Some(JulianDay::from_days(1_927_135.8747793)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::DeLuce,
        "DeLuce",
        &["De Luce", "DeLuce ayanamsa"],
        "Swiss Ephemeris DeLuce sidereal mode, documented by Astrodienst as a standard built-in ayanamsa option.",
        Some(JulianDay::from_days(2_451_545.0)),
        Some(Angle::from_degrees(23.245_522_556)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::Yukteshwar,
        "Yukteshwar",
        &["Yukteswar", "Sri Yukteswar", "Sri Yukteshwar", "Shri Yukteswar", "Shri Yukteshwar", "Yukteshwar ayanamsa"],
        "Swiss Ephemeris Yukteshwar sidereal mode, documented as a built-in ayanamsa option with a Sri Yukteswar-compatible naming family.",
        Some(JulianDay::from_days(2_415_020.0)),
        Some(Angle::from_degrees(360.0 - 338.917778)),
    ),
    AyanamsaDescriptor::new(
        Ayanamsa::PvrPushyaPaksha,
        "PVR Pushya-paksha",
        &[
            "Pushya-paksha",
            "Pushya Paksha",
            "PVR Pushya Paksha",
            "P.V.R. Narasimha Rao",
            "PVR",
            "True Pushya (PVRN Rao)",
        ],
        "P.V.R. Narasimha Rao's Pushya-paksha ayanamsa, exposed in Swiss Ephemeris as a built-in sidereal mode; catalogued metadata-only, not covered by the SE numeric gate.",
        Some(JulianDay::from_days(2_451_545.0)),
        Some(Angle::from_degrees(23.0)),
    ),
    AyanamsaDescriptor::new(
        Ayanamsa::Sheoran,
        "Sheoran",
        &["Sunil Sheoran", "Vedic Sheoran", "Vedic / Sheoran", "Sheoran ayanamsa", "\"Vedic\"/Sheoran"],
        "Sheoran's Vedic ayanamsa, anchored to the published zero point used by Swiss Ephemeris; catalogued metadata-only, not covered by the SE numeric gate.",
        Some(JulianDay::from_days(1_789_947.090_881)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::Hipparchus,
        "Hipparchus",
        &["Hipparchos"],
        "Swiss Ephemeris' Hipparchus sidereal mode, named for the Greek astronomer whose precession model underlies the historical reference frame.",
        Some(JulianDay::from_days(1_674_484.0)),
        Some(Angle::from_degrees(-9.333_333_333_333_334)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::BabylonianKugler1,
        "Babylonian (Kugler 1)",
        &["Babylonian/Kugler 1", "Babylonian Kugler 1", "Babylonian 1"],
        "Babylonian sidereal mode associated with Kugler's first reconstruction, with the Swiss Ephemeris zero point at JD 1833923.577692 (+0309/01/05 01:51:52.62 UT).",
        Some(JulianDay::from_days(1_833_923.577_692)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::BabylonianKugler2,
        "Babylonian (Kugler 2)",
        &["Babylonian/Kugler 2", "Babylonian Kugler 2", "Babylonian 2"],
        "Babylonian sidereal mode associated with Kugler's second reconstruction, with the Swiss Ephemeris zero point at JD 1797039.206820 (+0208/01/10 16:57:49.23 UT).",
        Some(JulianDay::from_days(1_797_039.206_820)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::BabylonianKugler3,
        "Babylonian (Kugler 3)",
        &["Babylonian/Kugler 3", "Babylonian Kugler 3", "Babylonian 3"],
        "Babylonian sidereal mode associated with Kugler's third reconstruction, with the Swiss Ephemeris zero point at JD 1774637.420172 (+0146/09/09 22:05:02.88 UT).",
        Some(JulianDay::from_days(1_774_637.420_172)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::BabylonianHuber,
        "Babylonian (Huber)",
        &["Babylonian/Huber", "Babylonian Huber"],
        "Babylonian sidereal mode associated with Huber's reconstruction.",
        Some(JulianDay::from_days(1_721_171.5)),
        Some(Angle::from_degrees(-0.120_555_555_555_555_55)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::BabylonianEtaPiscium,
        "Babylonian (Eta Piscium)",
        &["Babylonian/Eta Piscium", "Babylonian Eta Piscium", "Eta Piscium"],
        "Babylonian sidereal mode aligned to the Eta Piscium fiducial star.",
        Some(JulianDay::from_days(1_807_871.964_797)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::BabylonianAldebaran,
        "Babylonian (Aldebaran)",
        &["Babylonian/Aldebaran = 15 Tau", "Babylonian Aldebaran", "Babylonian 15 Tau", "15 Tau"],
        "Babylonian sidereal mode aligned to Aldebaran / 15 Taurus.",
        Some(JulianDay::from_days(1_801_643.133_503)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new(
        Ayanamsa::BabylonianHouse,
        "Babylonian (House)",
        &["Babylonian House", "BABYL_HOUSE"],
        "Custom-definition-only Babylonian sidereal label (alias BABYL_HOUSE); not a Swiss Ephemeris sidereal mode. Swiss Ephemeris defines no SE_SIDM code for it.",
        None,
        None,
    ),
    AyanamsaDescriptor::new(
        Ayanamsa::BabylonianSissy,
        "Babylonian (Sissy)",
        &["Babylonian Sissy", "BABYL_SISSY"],
        "Custom-definition-only Babylonian sidereal label (alias BABYL_SISSY); not a Swiss Ephemeris sidereal mode. Swiss Ephemeris defines no SE_SIDM code for it.",
        None,
        None,
    ),
    AyanamsaDescriptor::new(
        Ayanamsa::BabylonianTrueGeoc,
        "Babylonian (True Geoc)",
        &["Babylonian True Geoc", "BABYL_TRUE_GEOC"],
        "Custom-definition-only Babylonian sidereal label (alias BABYL_TRUE_GEOC); not a Swiss Ephemeris sidereal mode. Swiss Ephemeris defines no SE_SIDM code for it.",
        None,
        None,
    ),
    AyanamsaDescriptor::new(
        Ayanamsa::BabylonianTrueTopc,
        "Babylonian (True Topc)",
        &["Babylonian True Topc", "BABYL_TRUE_TOPC"],
        "Custom-definition-only Babylonian sidereal label (alias BABYL_TRUE_TOPC); not a Swiss Ephemeris sidereal mode. Swiss Ephemeris defines no SE_SIDM code for it.",
        None,
        None,
    ),
    AyanamsaDescriptor::new(
        Ayanamsa::BabylonianTrueObs,
        "Babylonian (True Obs)",
        &["Babylonian True Obs", "BABYL_TRUE_OBS"],
        "Custom-definition-only Babylonian sidereal label (alias BABYL_TRUE_OBS); not a Swiss Ephemeris sidereal mode. Swiss Ephemeris defines no SE_SIDM code for it.",
        None,
        None,
    ),
    AyanamsaDescriptor::new(
        Ayanamsa::BabylonianHouseObs,
        "Babylonian (House Obs)",
        &["Babylonian House Obs", "BABYL_HOUSE_OBS"],
        "Custom-definition-only Babylonian sidereal label (alias BABYL_HOUSE_OBS); not a Swiss Ephemeris sidereal mode. Swiss Ephemeris defines no SE_SIDM code for it.",
        None,
        None,
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::GalacticCenter,
        "Galactic Center",
        &["Galact. Center = 0 Sag", "Gal. Center = 0 Sag", "0 Sag", "Galactic center"],
        "Galactic-center sidereal reference mode fixed at 0 Sagittarius.",
        Some(JulianDay::from_days(1_746_340.540_490)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new(
        Ayanamsa::GalacticEquator,
        "Galactic Equator",
        &["Galactic equator", "Gal. Eq."],
        "Galactic-equator sidereal reference mode. The true/modern variant is anchored to the 1665728.603158 JD zero point described in the Swiss Ephemeris documentation.",
        Some(JulianDay::from_days(1_665_728.603_158)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::TruePushya,
        "True Pushya",
        &["Pushya", "True Pushya ayanamsa"],
        "True-nakshatra Pushya reference mode exposed by Swiss Ephemeris and anchored to the published zero date.",
        Some(JulianDay::from_days(1_855_769.248_315)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new(
        Ayanamsa::Udayagiri,
        "Udayagiri",
        &["Udayagiri ayanamsa"],
        "Udayagiri sidereal mode treated as the Lahiri/Chitrapaksha/Chitra Paksha 285 CE reference family in the Swiss Ephemeris interoperability catalog.",
        Some(JulianDay::from_days(1_825_235.164_583)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::DjwhalKhul,
        "Djwhal Khul",
        &["Djwhal", "Djwhal Khul ayanamsa"],
        "Djwhal Khul sidereal mode, anchored to the published zero date used by the Swiss Ephemeris family.",
        Some(JulianDay::from_days(2_415_020.0)),
        Some(Angle::from_degrees(360.0 - 333.0369024)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::JnBhasin,
        "JN Bhasin",
        &["J. N. Bhasin", "J.N. Bhasin", "Bhasin"],
        "J. N. Bhasin sidereal mode.",
        Some(JulianDay::from_days(2_415_020.0)),
        Some(Angle::from_degrees(360.0 - 338.634444)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::Suryasiddhanta499MeanSun,
        "Suryasiddhanta (Mean Sun)",
        &[
            "Suryasiddhanta, mean Sun",
            "Surya Siddhanta, mean Sun",
            "Suryasiddhanta mean sun",
            "Surya Siddhanta mean sun",
            "Suryasiddhanta MSUN",
            "Surya Siddhanta MSUN",
        ],
        "Suryasiddhanta mean-sun variant anchored to the published 514 CE zero point used by Swiss Ephemeris.",
        Some(JulianDay::from_days(1_903_396.8128654)),
        Some(Angle::from_degrees(-0.21463395)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::Aryabhata499MeanSun,
        "Aryabhata (Mean Sun)",
        &["Aryabhata, mean Sun", "Aryabhata mean sun", "Aryabhata MSUN"],
        "Aryabhata mean-sun variant anchored to the published 516 CE zero point used by Swiss Ephemeris.",
        Some(JulianDay::from_days(1_903_396.7895321)),
        Some(Angle::from_degrees(-0.23763238)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::BabylonianBritton,
        "Babylonian (Britton)",
        &["Babylonian/Britton", "Babylonian Britton"],
        "Babylonian sidereal mode associated with Britton's reconstruction, with the Swiss Ephemeris zero point at JD 1805415.712776 (+0230/12/17 05:06:23.86 UT).",
        Some(JulianDay::from_days(1_805_415.712_776)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::Aryabhata522,
        "Aryabhata (522 CE)",
        &["Aryabhata 522", "Aryabhata 522 CE"],
        "Aryabhata zero-point variant anchored to the published 522 CE reference date.",
        Some(JulianDay::from_days(1_911_797.740782065)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::LahiriVP285,
        "Lahiri (VP285)",
        &["Lahiri VP285", "VP285"],
        "Lahiri VP285 reference family anchored to the 285 CE mean-sun zero point used by Swiss Ephemeris.",
        Some(JulianDay::from_days(1_825_235.164_583)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::KrishnamurtiVP291,
        "Krishnamurti (VP291)",
        &["KP VP291", "Krishnamurti VP291", "Krishnamurti-Senthilathiban", "VP291"],
        "Krishnamurti variant aligned with the VP291 reference family and anchored to the published 291 CE zero point.",
        Some(JulianDay::from_days(1_827_424.663_554)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::TrueSheoran,
        "True Sheoran",
        &["Sheoran true", "True Sheoran ayanamsa"],
        "True-nakshatra Sheoran reference mode with the Swiss Ephemeris zero point at JD 1789947.090881 (+0188/08/09 14:10:52.11 UT).",
        Some(JulianDay::from_days(1_789_947.090_881)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::GalacticCenterRgilbrand,
        "Galactic Center (Rgilbrand)",
        &["Galactic Center (Gil Brand)", "Gil Brand", "Rgilbrand", "Galactic center Rgilbrand"],
        "Galactic-center reference mode attributed to Rgilbrand, with the Swiss Ephemeris zero point at JD 1861740.329525 (+0385/03/03 19:54:30.99 UT).",
        Some(JulianDay::from_days(1_861_740.329_525)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::GalacticCenterMardyks,
        "Galactic Center (Mardyks)",
        &["Skydram", "Skydram/Galactic Alignment", "Skydram (Mardyks)", "Mardyks", "Galactic center Mardyks"],
        "Galactic-center reference mode attributed to Mardyks, with the Swiss Ephemeris zero point at JD 1662951.794251 (-0160/11/27 07:03:43.27 UT).",
        Some(JulianDay::from_days(1_662_951.794_251)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::GalacticCenterMulaWilhelm,
        "Galactic Center (Mula/Wilhelm)",
        &["Dhruva/Gal.Center/Mula (Wilhelm)", "Mula Wilhelm", "Wilhelm", "Galactic center Mula/Wilhelm"],
        "Galactic-center reference mode aligned to the Mula/Wilhelm tradition, with the Swiss Ephemeris zero point at JD 1946834.818321 (+0618/02/25 07:38:22.96 UT).",
        Some(JulianDay::from_days(1_946_834.818_321)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new(
        Ayanamsa::DhruvaGalacticCenterMula,
        "Dhruva Galactic Center (Middle Mula)",
        &[
            "Dhruva/Gal.Center/Mula",
            "Dhruva Galactic Center Middle Mula",
            "Dhruva Middle Mula",
            "Middle of Mula",
        ],
        "Dhruva projection of the Galactic Center to the middle of Mula for interoperability with Wilhelm-style sidereal selections.",
        Some(JulianDay::from_days(1_946_834.818_321)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::GalacticCenterCochrane,
        "Galactic Center (Cochrane)",
        &["Cochrane (Gal.Center = 0 Cap)", "Gal. Center = 0 Cap", "Cochrane", "Galactic center Cochrane", "David Cochrane"],
        "Galactic-center reference mode attributed to Cochrane and catalogued with the Swiss Ephemeris zero-point epoch.",
        Some(JulianDay::from_days(1_662_951.794_251)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::GalacticEquatorIau1958,
        "Galactic Equator (IAU 1958)",
        &["Galactic Equator (IAU1958)", "IAU 1958", "Galactic equator IAU 1958"],
        "Galactic-equator reference mode using the IAU 1958 definition.",
        Some(JulianDay::from_days(1_667_118.376_332)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::GalacticEquatorTrue,
        "Galactic Equator (True)",
        &["True galactic equator", "Galactic equator true"],
        "Galactic-equator reference mode using the true-galactic definition. The true/modern variant is anchored to the 1665728.603158 JD zero point described in the Swiss Ephemeris documentation.",
        Some(JulianDay::from_days(1_665_728.603_158)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::GalacticEquatorMula,
        "Galactic Equator (Mula)",
        &["Galactic Equator mid-Mula", "Mula galactic equator", "Galactic equator Mula"],
        "Galactic-equator reference mode aligned to the Mula tradition and anchored to the Swiss Ephemeris mid-Mula zero point.",
        Some(JulianDay::from_days(1_840_527.426_262)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::GalacticEquatorFiorenza,
        "Galactic Equator (Fiorenza)",
        &["Fiorenza", "Galactic equator Fiorenza", "Nick Anthony Fiorenza"],
        "Galactic-equator reference mode attributed to Fiorenza and catalogued with the Swiss Ephemeris J2000.0 reference epoch and 25° zero-point offset.",
        Some(JulianDay::from_days(2_451_544.5)),
        Some(Angle::from_degrees(25.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::ValensMoon,
        "Valens Moon",
        &["Vettius Valens", "Valens", "Moon", "Moon sign", "Moon sign ayanamsa", "Valens Moon ayanamsa"],
        "Valens Moon sidereal mode, catalogued with the Swiss Ephemeris reference epoch and offset from the header metadata.",
        Some(JulianDay::from_days(1_775_845.5)),
        Some(Angle::from_degrees(-2.942_2)),
    ),
];

pub(crate) static BUILT_IN_AYANAMSAS: [AyanamsaDescriptor; 59] = [
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::Lahiri,
        "Lahiri",
        &[
            "Chitra Paksha",
            "Chitrapaksha",
            "Chitra-paksha",
            "Lahiri Ayanamsha",
            "Lahiri ayanamsa",
        ],
        "Default Indian sidereal standard in many astrology workflows.",
        Some(JulianDay::from_days(2_435_553.5)),
        Some(Angle::from_degrees(23.245_524_743)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::Raman,
        "Raman",
        &[
            "B. V. Raman",
            "B.V. Raman",
            "B V Raman",
            "Raman Ayanamsha",
            "Raman ayanamsa",
        ],
        "Popular named sidereal offset used in classical astrology software.",
        Some(JulianDay::from_days(2_415_020.0)),
        Some(Angle::from_degrees(21.014_44)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::Krishnamurti,
        "Krishnamurti",
        &[
            "KP",
            "Krishnamurti Ayanamsha",
            "Krishnamurti ayanamsa",
            "Krishnamurti (Swiss)",
            "Krishnamurti Paddhati",
            "KP ayanamsa",
        ],
        "Krishnamurti Paddhati ayanamsa.",
        Some(JulianDay::from_days(2_415_020.0)),
        Some(Angle::from_degrees(22.363_889)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::FaganBradley,
        "Fagan/Bradley",
        &[
            "Fagan/Bradley Ayanamsha",
            "Fagan Bradley",
            "Fagan-Bradley",
            "Fagan / Bradley",
        ],
        "Western sidereal reference used by several astrology packages.",
        Some(JulianDay::from_days(2_433_282.423_46)),
        Some(Angle::from_degrees(24.042_044_444)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::TrueChitra,
        "True Chitra",
        &["Chitra", "True Chitra ayanamsa"],
        "True Chitra / Chitra-based sidereal variant.",
        Some(JulianDay::from_days(2_435_553.5)),
        Some(Angle::from_degrees(23.245_524_743)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::TrueCitra,
        "True Citra",
        &[
            "True Citra ayanamsa",
            "True Citra Paksha",
            "True Chitra Paksha",
            "True Chitrapaksha",
        ],
        "True Citra sidereal mode with the published zero point used by Swiss Ephemeris-style interoperability tables.",
        Some(JulianDay::from_days(1_825_182.872_330)),
        Some(Angle::from_degrees(50.256_748_3)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::J2000,
        "J2000",
        &["J2000.0"],
        "Swiss Ephemeris J2000 sidereal frame anchored to the standard J2000.0 epoch.",
        Some(JulianDay::from_days(2_451_545.0)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::J1900,
        "J1900",
        &["J1900.0"],
        "Swiss Ephemeris J1900 sidereal frame anchored to the standard J1900.0 epoch.",
        Some(JulianDay::from_days(2_415_020.0)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::B1950,
        "B1950",
        &["B1950.0"],
        "Swiss Ephemeris B1950 sidereal frame anchored to the FK4 B1950.0 epoch.",
        Some(JulianDay::from_days(2_433_282.423_459_05)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::TrueRevati,
        "True Revati",
        &["True Revati ayanamsa"],
        "True-nakshatra mode with the Revati reference point fixed to the Swiss Ephemeris zero date.",
        Some(JulianDay::from_days(1_926_902.658_267)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::TrueMula,
        "True Mula",
        &["True Mula (Chandra Hari)", "True Mula ayanamsa", "Chandra Hari"],
        "True-nakshatra mode with the Mula reference point fixed to the Swiss Ephemeris zero date.",
        Some(JulianDay::from_days(1_805_889.671_313)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::SuryasiddhantaRevati,
        "Suryasiddhanta (Revati)",
        &["SS Revati", "Suryasiddhanta Revati", "Surya Siddhanta Revati"],
        "Swiss Ephemeris SS Revati mode, anchored to the published Revati zero point used by the Surya Siddhanta family.",
        Some(JulianDay::from_days(1_903_396.8128654)),
        Some(Angle::from_degrees(-0.79167046)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::SuryasiddhantaCitra,
        "Suryasiddhanta (Citra)",
        &["SS Citra", "Suryasiddhanta Citra", "Surya Siddhanta Citra"],
        "Swiss Ephemeris SS Citra mode, anchored to the published Citra zero point used by the Surya Siddhanta family.",
        Some(JulianDay::from_days(1_903_396.8128654)),
        Some(Angle::from_degrees(2.11070444)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::LahiriIcrc,
        "Lahiri (ICRC)",
        &["ICRC Lahiri", "Lahiri ICRC"],
        "The 1956 Indian Calendar Reform Committee standard with a round 23°15′ reference value.",
        Some(JulianDay::from_days(2_435_553.5)),
        Some(Angle::from_degrees(23.25 - 0.00464207)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::Lahiri1940,
        "Lahiri (1940)",
        &["Lahiri original", "Panchanga Darpan Lahiri"],
        "Lahiri's earlier zero-date variant published in Panchanga Darpan.",
        Some(JulianDay::from_days(2_415_020.0)),
        Some(Angle::from_degrees(22.44597222)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::UshaShashi,
        "Usha Shashi",
        &["Ushashashi", "Usha-Shashi", "Usha/Shashi", "Usha / Shashi", "Usha Shashi ayanamsa", "Revati"],
        "Revati-bound zero-point variant used in the Greek-Arabic-Hindu tradition.",
        Some(JulianDay::from_days(2_415_020.0)),
        Some(Angle::from_degrees(360.0 - 341.33904)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::Suryasiddhanta499,
        "Suryasiddhanta (499 CE)",
        &["Suryasiddhanta 499", "Surya Siddhanta 499", "Suryasiddhanta 499 CE", "Surya Siddhanta 499 CE", "Surya Siddhanta", "Suryasiddhanta"],
        "Suryasiddhanta zero-point variant anchored to the 499 CE equinox.",
        Some(JulianDay::from_days(1_903_396.8128654)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::Aryabhata499,
        "Aryabhata (499 CE)",
        &[
            "Aryabhata 499",
            "Aryabhata 499 CE",
            "Aryabhata",
            "Aryabhatan Kaliyuga",
            "Aryabhata Kaliyuga",
        ],
        "Aryabhata zero-point variant anchored to the 499 CE dawn tradition.",
        Some(JulianDay::from_days(1_903_396.7895321)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::Sassanian,
        "Sassanian",
        &["Zij al-Shah", "Sasanian"],
        "Sassanian zero-point variant anchored to the 564 CE table-reform epoch.",
        Some(JulianDay::from_days(1_927_135.8747793)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::DeLuce,
        "DeLuce",
        &["De Luce", "DeLuce ayanamsa"],
        "Swiss Ephemeris DeLuce sidereal mode, documented by Astrodienst as a standard built-in ayanamsa option.",
        Some(JulianDay::from_days(2_451_545.0)),
        Some(Angle::from_degrees(23.245_522_556)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::Yukteshwar,
        "Yukteshwar",
        &["Yukteswar", "Sri Yukteswar", "Sri Yukteshwar", "Shri Yukteswar", "Shri Yukteshwar", "Yukteshwar ayanamsa"],
        "Swiss Ephemeris Yukteshwar sidereal mode, documented as a built-in ayanamsa option with a Sri Yukteswar-compatible naming family.",
        Some(JulianDay::from_days(2_415_020.0)),
        Some(Angle::from_degrees(360.0 - 338.917778)),
    ),
    AyanamsaDescriptor::new(
        Ayanamsa::PvrPushyaPaksha,
        "PVR Pushya-paksha",
        &[
            "Pushya-paksha",
            "Pushya Paksha",
            "PVR Pushya Paksha",
            "P.V.R. Narasimha Rao",
            "PVR",
            "True Pushya (PVRN Rao)",
        ],
        "P.V.R. Narasimha Rao's Pushya-paksha ayanamsa, exposed in Swiss Ephemeris as a built-in sidereal mode; catalogued metadata-only, not covered by the SE numeric gate.",
        Some(JulianDay::from_days(2_451_545.0)),
        Some(Angle::from_degrees(23.0)),
    ),
    AyanamsaDescriptor::new(
        Ayanamsa::Sheoran,
        "Sheoran",
        &["Sunil Sheoran", "Vedic Sheoran", "Vedic / Sheoran", "Sheoran ayanamsa", "\"Vedic\"/Sheoran"],
        "Sheoran's Vedic ayanamsa, anchored to the published zero point used by Swiss Ephemeris; catalogued metadata-only, not covered by the SE numeric gate.",
        Some(JulianDay::from_days(1_789_947.090_881)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::Hipparchus,
        "Hipparchus",
        &["Hipparchos"],
        "Swiss Ephemeris' Hipparchus sidereal mode, named for the Greek astronomer whose precession model underlies the historical reference frame.",
        Some(JulianDay::from_days(1_674_484.0)),
        Some(Angle::from_degrees(-9.333_333_333_333_334)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::BabylonianKugler1,
        "Babylonian (Kugler 1)",
        &["Babylonian/Kugler 1", "Babylonian Kugler 1", "Babylonian 1"],
        "Babylonian sidereal mode associated with Kugler's first reconstruction, with the Swiss Ephemeris zero point at JD 1833923.577692 (+0309/01/05 01:51:52.62 UT).",
        Some(JulianDay::from_days(1_833_923.577_692)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::BabylonianKugler2,
        "Babylonian (Kugler 2)",
        &["Babylonian/Kugler 2", "Babylonian Kugler 2", "Babylonian 2"],
        "Babylonian sidereal mode associated with Kugler's second reconstruction, with the Swiss Ephemeris zero point at JD 1797039.206820 (+0208/01/10 16:57:49.23 UT).",
        Some(JulianDay::from_days(1_797_039.206_820)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::BabylonianKugler3,
        "Babylonian (Kugler 3)",
        &["Babylonian/Kugler 3", "Babylonian Kugler 3", "Babylonian 3"],
        "Babylonian sidereal mode associated with Kugler's third reconstruction, with the Swiss Ephemeris zero point at JD 1774637.420172 (+0146/09/09 22:05:02.88 UT).",
        Some(JulianDay::from_days(1_774_637.420_172)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::BabylonianHuber,
        "Babylonian (Huber)",
        &["Babylonian/Huber", "Babylonian Huber"],
        "Babylonian sidereal mode associated with Huber's reconstruction.",
        Some(JulianDay::from_days(1_721_171.5)),
        Some(Angle::from_degrees(-0.120_555_555_555_555_55)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::BabylonianEtaPiscium,
        "Babylonian (Eta Piscium)",
        &["Babylonian/Eta Piscium", "Babylonian Eta Piscium", "Eta Piscium"],
        "Babylonian sidereal mode aligned to the Eta Piscium fiducial star.",
        Some(JulianDay::from_days(1_807_871.964_797)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::BabylonianAldebaran,
        "Babylonian (Aldebaran)",
        &["Babylonian/Aldebaran = 15 Tau", "Babylonian Aldebaran", "Babylonian 15 Tau", "15 Tau"],
        "Babylonian sidereal mode aligned to Aldebaran / 15 Taurus.",
        Some(JulianDay::from_days(1_801_643.133_503)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new(
        Ayanamsa::BabylonianHouse,
        "Babylonian (House)",
        &["Babylonian House", "BABYL_HOUSE"],
        "Custom-definition-only Babylonian sidereal label (alias BABYL_HOUSE); not a Swiss Ephemeris sidereal mode. Swiss Ephemeris defines no SE_SIDM code for it.",
        None,
        None,
    ),
    AyanamsaDescriptor::new(
        Ayanamsa::BabylonianSissy,
        "Babylonian (Sissy)",
        &["Babylonian Sissy", "BABYL_SISSY"],
        "Custom-definition-only Babylonian sidereal label (alias BABYL_SISSY); not a Swiss Ephemeris sidereal mode. Swiss Ephemeris defines no SE_SIDM code for it.",
        None,
        None,
    ),
    AyanamsaDescriptor::new(
        Ayanamsa::BabylonianTrueGeoc,
        "Babylonian (True Geoc)",
        &["Babylonian True Geoc", "BABYL_TRUE_GEOC"],
        "Custom-definition-only Babylonian sidereal label (alias BABYL_TRUE_GEOC); not a Swiss Ephemeris sidereal mode. Swiss Ephemeris defines no SE_SIDM code for it.",
        None,
        None,
    ),
    AyanamsaDescriptor::new(
        Ayanamsa::BabylonianTrueTopc,
        "Babylonian (True Topc)",
        &["Babylonian True Topc", "BABYL_TRUE_TOPC"],
        "Custom-definition-only Babylonian sidereal label (alias BABYL_TRUE_TOPC); not a Swiss Ephemeris sidereal mode. Swiss Ephemeris defines no SE_SIDM code for it.",
        None,
        None,
    ),
    AyanamsaDescriptor::new(
        Ayanamsa::BabylonianTrueObs,
        "Babylonian (True Obs)",
        &["Babylonian True Obs", "BABYL_TRUE_OBS"],
        "Custom-definition-only Babylonian sidereal label (alias BABYL_TRUE_OBS); not a Swiss Ephemeris sidereal mode. Swiss Ephemeris defines no SE_SIDM code for it.",
        None,
        None,
    ),
    AyanamsaDescriptor::new(
        Ayanamsa::BabylonianHouseObs,
        "Babylonian (House Obs)",
        &["Babylonian House Obs", "BABYL_HOUSE_OBS"],
        "Custom-definition-only Babylonian sidereal label (alias BABYL_HOUSE_OBS); not a Swiss Ephemeris sidereal mode. Swiss Ephemeris defines no SE_SIDM code for it.",
        None,
        None,
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::GalacticCenter,
        "Galactic Center",
        &["Galact. Center = 0 Sag", "Gal. Center = 0 Sag", "0 Sag", "Galactic center"],
        "Galactic-center sidereal reference mode fixed at 0 Sagittarius.",
        Some(JulianDay::from_days(1_746_340.540_490)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new(
        Ayanamsa::GalacticEquator,
        "Galactic Equator",
        &["Galactic equator", "Gal. Eq."],
        "Galactic-equator sidereal reference mode. The true/modern variant is anchored to the 1665728.603158 JD zero point described in the Swiss Ephemeris documentation.",
        Some(JulianDay::from_days(1_665_728.603_158)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::TruePushya,
        "True Pushya",
        &["Pushya", "True Pushya ayanamsa"],
        "True-nakshatra Pushya reference mode exposed by Swiss Ephemeris and anchored to the published zero date.",
        Some(JulianDay::from_days(1_855_769.248_315)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new(
        Ayanamsa::Udayagiri,
        "Udayagiri",
        &["Udayagiri ayanamsa"],
        "Udayagiri sidereal mode treated as the Lahiri/Chitrapaksha/Chitra Paksha 285 CE reference family in the Swiss Ephemeris interoperability catalog.",
        Some(JulianDay::from_days(1_825_235.164_583)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::DjwhalKhul,
        "Djwhal Khul",
        &["Djwhal", "Djwhal Khul ayanamsa"],
        "Djwhal Khul sidereal mode, anchored to the published zero date used by the Swiss Ephemeris family.",
        Some(JulianDay::from_days(2_415_020.0)),
        Some(Angle::from_degrees(360.0 - 333.0369024)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::JnBhasin,
        "JN Bhasin",
        &["J. N. Bhasin", "J.N. Bhasin", "Bhasin"],
        "J. N. Bhasin sidereal mode.",
        Some(JulianDay::from_days(2_415_020.0)),
        Some(Angle::from_degrees(360.0 - 338.634444)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::Suryasiddhanta499MeanSun,
        "Suryasiddhanta (Mean Sun)",
        &[
            "Suryasiddhanta, mean Sun",
            "Surya Siddhanta, mean Sun",
            "Suryasiddhanta mean sun",
            "Surya Siddhanta mean sun",
            "Suryasiddhanta MSUN",
            "Surya Siddhanta MSUN",
        ],
        "Suryasiddhanta mean-sun variant anchored to the published 514 CE zero point used by Swiss Ephemeris.",
        Some(JulianDay::from_days(1_903_396.8128654)),
        Some(Angle::from_degrees(-0.21463395)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::Aryabhata499MeanSun,
        "Aryabhata (Mean Sun)",
        &["Aryabhata, mean Sun", "Aryabhata mean sun", "Aryabhata MSUN"],
        "Aryabhata mean-sun variant anchored to the published 516 CE zero point used by Swiss Ephemeris.",
        Some(JulianDay::from_days(1_903_396.7895321)),
        Some(Angle::from_degrees(-0.23763238)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::BabylonianBritton,
        "Babylonian (Britton)",
        &["Babylonian/Britton", "Babylonian Britton"],
        "Babylonian sidereal mode associated with Britton's reconstruction, with the Swiss Ephemeris zero point at JD 1805415.712776 (+0230/12/17 05:06:23.86 UT).",
        Some(JulianDay::from_days(1_805_415.712_776)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::Aryabhata522,
        "Aryabhata (522 CE)",
        &["Aryabhata 522", "Aryabhata 522 CE"],
        "Aryabhata zero-point variant anchored to the published 522 CE reference date.",
        Some(JulianDay::from_days(1_911_797.740782065)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::LahiriVP285,
        "Lahiri (VP285)",
        &["Lahiri VP285", "VP285"],
        "Lahiri VP285 reference family anchored to the 285 CE mean-sun zero point used by Swiss Ephemeris.",
        Some(JulianDay::from_days(1_825_235.164_583)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::KrishnamurtiVP291,
        "Krishnamurti (VP291)",
        &["KP VP291", "Krishnamurti VP291", "Krishnamurti-Senthilathiban", "VP291"],
        "Krishnamurti variant aligned with the VP291 reference family and anchored to the published 291 CE zero point.",
        Some(JulianDay::from_days(1_827_424.663_554)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::TrueSheoran,
        "True Sheoran",
        &["Sheoran true", "True Sheoran ayanamsa"],
        "True-nakshatra Sheoran reference mode with the Swiss Ephemeris zero point at JD 1789947.090881 (+0188/08/09 14:10:52.11 UT).",
        Some(JulianDay::from_days(1_789_947.090_881)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::GalacticCenterRgilbrand,
        "Galactic Center (Rgilbrand)",
        &["Galactic Center (Gil Brand)", "Gil Brand", "Rgilbrand", "Galactic center Rgilbrand"],
        "Galactic-center reference mode attributed to Rgilbrand, with the Swiss Ephemeris zero point at JD 1861740.329525 (+0385/03/03 19:54:30.99 UT).",
        Some(JulianDay::from_days(1_861_740.329_525)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::GalacticCenterMardyks,
        "Galactic Center (Mardyks)",
        &["Skydram", "Skydram/Galactic Alignment", "Skydram (Mardyks)", "Mardyks", "Galactic center Mardyks"],
        "Galactic-center reference mode attributed to Mardyks, with the Swiss Ephemeris zero point at JD 1662951.794251 (-0160/11/27 07:03:43.27 UT).",
        Some(JulianDay::from_days(1_662_951.794_251)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::GalacticCenterMulaWilhelm,
        "Galactic Center (Mula/Wilhelm)",
        &["Dhruva/Gal.Center/Mula (Wilhelm)", "Mula Wilhelm", "Wilhelm", "Galactic center Mula/Wilhelm"],
        "Galactic-center reference mode aligned to the Mula/Wilhelm tradition, with the Swiss Ephemeris zero point at JD 1946834.818321 (+0618/02/25 07:38:22.96 UT).",
        Some(JulianDay::from_days(1_946_834.818_321)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new(
        Ayanamsa::DhruvaGalacticCenterMula,
        "Dhruva Galactic Center (Middle Mula)",
        &[
            "Dhruva/Gal.Center/Mula",
            "Dhruva Galactic Center Middle Mula",
            "Dhruva Middle Mula",
            "Middle of Mula",
        ],
        "Dhruva projection of the Galactic Center to the middle of Mula for interoperability with Wilhelm-style sidereal selections.",
        Some(JulianDay::from_days(1_946_834.818_321)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::GalacticCenterCochrane,
        "Galactic Center (Cochrane)",
        &["Cochrane (Gal.Center = 0 Cap)", "Gal. Center = 0 Cap", "Cochrane", "Galactic center Cochrane", "David Cochrane"],
        "Galactic-center reference mode attributed to Cochrane and catalogued with the Swiss Ephemeris zero-point epoch.",
        Some(JulianDay::from_days(1_662_951.794_251)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::GalacticEquatorIau1958,
        "Galactic Equator (IAU 1958)",
        &["Galactic Equator (IAU1958)", "IAU 1958", "Galactic equator IAU 1958"],
        "Galactic-equator reference mode using the IAU 1958 definition.",
        Some(JulianDay::from_days(1_667_118.376_332)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::GalacticEquatorTrue,
        "Galactic Equator (True)",
        &["True galactic equator", "Galactic equator true"],
        "Galactic-equator reference mode using the true-galactic definition. The true/modern variant is anchored to the 1665728.603158 JD zero point described in the Swiss Ephemeris documentation.",
        Some(JulianDay::from_days(1_665_728.603_158)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::GalacticEquatorMula,
        "Galactic Equator (Mula)",
        &["Galactic Equator mid-Mula", "Mula galactic equator", "Galactic equator Mula"],
        "Galactic-equator reference mode aligned to the Mula tradition and anchored to the Swiss Ephemeris mid-Mula zero point.",
        Some(JulianDay::from_days(1_840_527.426_262)),
        Some(Angle::from_degrees(0.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::GalacticEquatorFiorenza,
        "Galactic Equator (Fiorenza)",
        &["Fiorenza", "Galactic equator Fiorenza", "Nick Anthony Fiorenza"],
        "Galactic-equator reference mode attributed to Fiorenza and catalogued with the Swiss Ephemeris J2000.0 reference epoch and 25° zero-point offset.",
        Some(JulianDay::from_days(2_451_544.5)),
        Some(Angle::from_degrees(25.0)),
    ),
    AyanamsaDescriptor::new_release_grade(
        Ayanamsa::ValensMoon,
        "Valens Moon",
        &["Vettius Valens", "Valens", "Moon", "Moon sign", "Moon sign ayanamsa", "Valens Moon ayanamsa"],
        "Valens Moon sidereal mode, catalogued with the Swiss Ephemeris reference epoch and offset from the header metadata.",
        Some(JulianDay::from_days(1_775_845.5)),
        Some(Angle::from_degrees(-2.942_2)),
    ),
];

#[cfg(test)]
mod tests;
