//! Committed cubic polynomials for the "fitted-offset" ayanamsa modes —
//! offset/historical modes whose linear anchor+precession model missed the
//! OffsetDefined ceiling, re-fit by `tools/se-ayanamsa-reference fit` to Swiss
//! Ephemeris **mean** ayanamsa over 1900–2100. Same smooth-cubic rationale as
//! `truestar.rs`/`galactic.rs`.
//!
//! Provenance: Swiss Ephemeris 2.10.03 (libswisseph-sys 0.1.2), MEAN_IFLAG
//! (`SEFLG_NONUT | SEFLG_NOABERR`). Per-mode `SE_SIDM` code:
//!   DeLuce=2, BabylonianKugler1=9, BabylonianKugler2=10, BabylonianKugler3=11,
//!   BabylonianHuber=12, BabylonianEtaPiscium=13, BabylonianAldebaran=14,
//!   Hipparchus=15, BabylonianBritton=38, ValensMoon=42, LahiriVP285=44,
//!   KrishnamurtiVP291=45.
#![forbid(unsafe_code)]

use pleiades_types::Ayanamsa;

use crate::truestar::{eval, TRUE_STAR_FIT_JD_MAX, TRUE_STAR_FIT_JD_MIN};

// Generated by se-ayanamsa-reference fit — paste the printed lines here.
pub(crate) const DELUCE_COEFFS: [f64; 4] = [2.781575277442e1, 1.396878320924e0, 3.059011257009e-4, 7.253107131446e-9];
pub(crate) const BABYLONIANKUGLER1_COEFFS: [f64; 4] = [2.353363986390e1, 1.396877045876e0, 3.058417200716e-4, 7.880854111415e-9];
pub(crate) const BABYLONIANKUGLER2_COEFFS: [f64; 4] = [2.493363986390e1, 1.396877045876e0, 3.058417201569e-4, 7.880852659688e-9];
pub(crate) const BABYLONIANKUGLER3_COEFFS: [f64; 4] = [2.578363986390e1, 1.396877045876e0, 3.058417200716e-4, 7.880868628683e-9];
pub(crate) const BABYLONIANHUBER_COEFFS: [f64; 4] = [2.473363986390e1, 1.396877045876e0, 3.058417201569e-4, 7.880906373579e-9];
pub(crate) const BABYLONIANETAPISCIUM_COEFFS: [f64; 4] = [2.452252793528e1, 1.396876661735e0, 3.058245917305e-4, 8.071047739142e-9];
pub(crate) const BABYLONIANALDEBARAN_COEFFS: [f64; 4] = [2.475892388390e1, 1.396877045876e0, 3.058417201203e-4, 7.880710390465e-9];
pub(crate) const HIPPARCHUS_COEFFS: [f64; 4] = [2.024778809429e1, 1.396876681587e0, 3.058254687196e-4, 8.061170190192e-9];
pub(crate) const BABYLONIANBRITTON_COEFFS: [f64; 4] = [2.461575277442e1, 1.396878320925e0, 3.059011256887e-4, 7.253069386550e-9];
pub(crate) const VALENSMOON_COEFFS: [f64; 4] = [2.279560929939e1, 1.396880089038e0, 3.059911244107e-4, 6.393172423444e-9];
pub(crate) const LAHIRIVP285_COEFFS: [f64; 4] = [2.386348120291e1, 1.396881534321e0, 3.060730389978e-4, 5.702090959635e-9];
pub(crate) const KRISHNAMURTIVP291_COEFFS: [f64; 4] = [2.378036495719e1, 1.396881595131e0, 3.060766854084e-4, 5.673158045088e-9];

/// Fitted-offset sidereal offset in degrees, or `None` if `ayanamsa` is not a
/// committed fitted-offset mode or `jd_tt` is outside the fit window (fail-closed).
pub(crate) fn fitted_offset_degrees(ayanamsa: &Ayanamsa, jd_tt: f64) -> Option<f64> {
    let coeffs = match ayanamsa {
        Ayanamsa::DeLuce => &DELUCE_COEFFS,
        Ayanamsa::BabylonianKugler1 => &BABYLONIANKUGLER1_COEFFS,
        Ayanamsa::BabylonianKugler2 => &BABYLONIANKUGLER2_COEFFS,
        Ayanamsa::BabylonianKugler3 => &BABYLONIANKUGLER3_COEFFS,
        Ayanamsa::BabylonianHuber => &BABYLONIANHUBER_COEFFS,
        Ayanamsa::BabylonianEtaPiscium => &BABYLONIANETAPISCIUM_COEFFS,
        Ayanamsa::BabylonianAldebaran => &BABYLONIANALDEBARAN_COEFFS,
        Ayanamsa::Hipparchus => &HIPPARCHUS_COEFFS,
        Ayanamsa::BabylonianBritton => &BABYLONIANBRITTON_COEFFS,
        Ayanamsa::ValensMoon => &VALENSMOON_COEFFS,
        Ayanamsa::LahiriVP285 => &LAHIRIVP285_COEFFS,
        Ayanamsa::KrishnamurtiVP291 => &KRISHNAMURTIVP291_COEFFS,
        _ => return None,
    };
    if !(TRUE_STAR_FIT_JD_MIN..=TRUE_STAR_FIT_JD_MAX).contains(&jd_tt) {
        return None;
    }
    Some(eval(coeffs, jd_tt))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn promoted_fitted_offset_modes_return_some_in_window() {
        let jd = 2_451_545.0;
        for m in [
            Ayanamsa::DeLuce,
            Ayanamsa::BabylonianKugler1,
            Ayanamsa::BabylonianKugler2,
            Ayanamsa::BabylonianKugler3,
            Ayanamsa::BabylonianHuber,
            Ayanamsa::BabylonianEtaPiscium,
            Ayanamsa::BabylonianAldebaran,
            Ayanamsa::Hipparchus,
            Ayanamsa::BabylonianBritton,
            Ayanamsa::ValensMoon,
            Ayanamsa::LahiriVP285,
            Ayanamsa::KrishnamurtiVP291,
        ] {
            assert!(
                fitted_offset_degrees(&m, jd).is_some(),
                "{m:?} in-window should be Some"
            );
            assert!(
                fitted_offset_degrees(&m, 2_300_000.0).is_none(),
                "{m:?} pre-window should be None"
            );
        }
        assert!(fitted_offset_degrees(&Ayanamsa::Lahiri, jd).is_none());
    }
}
