//! Committed cubic polynomials for the galactic-reference ayanamsa modes
//! (galactic center / galactic equator families), fit by
//! `tools/se-ayanamsa-reference fit` to Swiss Ephemeris **mean** ayanamsa over
//! 1900–2100. Same smooth-cubic rationale as `truestar.rs`.
#![forbid(unsafe_code)]

use pleiades_types::Ayanamsa;

use crate::truestar::{eval, TRUE_STAR_FIT_JD_MAX, TRUE_STAR_FIT_JD_MIN};

// Generated by se-ayanamsa-reference fit — paste the printed lines here.
pub(crate) const GALACTICCENTER_COEFFS: [f64; 4] = [
    2.685170101572e1,
    1.396858753834e0,
    3.123943025530e-4,
    3.538065592772e-8,
];
pub(crate) const GALACTICCENTERRGILBRAND_COEFFS: [f64; 4] = [
    2.247475999872e1,
    1.396858753834e0,
    3.123943025286e-4,
    3.538063415182e-8,
];
pub(crate) const GALACTICEQUATORIAU1958_COEFFS: [f64; 4] = [
    3.002317246952e1,
    1.404337887134e0,
    2.986828471216e-4,
    -5.560485029926e-8,
];
pub(crate) const GALACTICEQUATORTRUE_COEFFS: [f64; 4] = [
    3.007609218066e1,
    1.404335698331e0,
    2.986538407836e-4,
    -5.554923609839e-8,
];
pub(crate) const GALACTICEQUATORMULA_COEFFS: [f64; 4] = [
    2.340942551396e1,
    1.404335698331e0,
    2.986538407227e-4,
    -5.554928255365e-8,
];
pub(crate) const GALACTICCENTERMARDYKS_COEFFS: [f64; 4] = [
    3.001779387730e1,
    1.396887832151e0,
    3.071213262971e-4,
    3.701533075907e-9,
];
pub(crate) const GALACTICCENTERMULAWILHELM_COEFFS: [f64; 4] = [
    2.004513584862e1,
    1.458603497122e0,
    4.871228097402e-4,
    -7.008821187119e-6,
];
pub(crate) const GALACTICCENTERCOCHRANE_COEFFS: [f64; 4] = [
    3.568517010157e2,
    1.396858753834e0,
    3.123943025895e-4,
    3.538073722442e-8,
];
pub(crate) const GALACTICEQUATORFIORENZA_COEFFS: [f64; 4] = [
    2.500001909466e1,
    1.396887828788e0,
    3.071220785656e-4,
    3.704620898749e-9,
];

/// Galactic sidereal offset in degrees, or `None` if `ayanamsa` is not a
/// committed galactic mode or `jd_tt` is outside the fit window (fail-closed).
pub(crate) fn galactic_offset_degrees(ayanamsa: &Ayanamsa, jd_tt: f64) -> Option<f64> {
    let coeffs = match ayanamsa {
        Ayanamsa::GalacticCenter => &GALACTICCENTER_COEFFS,
        Ayanamsa::GalacticCenterRgilbrand => &GALACTICCENTERRGILBRAND_COEFFS,
        Ayanamsa::GalacticEquatorIau1958 => &GALACTICEQUATORIAU1958_COEFFS,
        Ayanamsa::GalacticEquatorTrue => &GALACTICEQUATORTRUE_COEFFS,
        Ayanamsa::GalacticEquatorMula => &GALACTICEQUATORMULA_COEFFS,
        Ayanamsa::GalacticCenterMardyks => &GALACTICCENTERMARDYKS_COEFFS,
        Ayanamsa::GalacticCenterMulaWilhelm => &GALACTICCENTERMULAWILHELM_COEFFS,
        Ayanamsa::GalacticCenterCochrane => &GALACTICCENTERCOCHRANE_COEFFS,
        Ayanamsa::GalacticEquatorFiorenza => &GALACTICEQUATORFIORENZA_COEFFS,
        _ => return None,
    };
    if !(TRUE_STAR_FIT_JD_MIN..=TRUE_STAR_FIT_JD_MAX).contains(&jd_tt) {
        return None;
    }
    Some(eval(coeffs, jd_tt))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn promoted_galactic_modes_return_some_in_window() {
        let jd = 2_451_545.0;
        for m in [
            Ayanamsa::GalacticCenter,
            Ayanamsa::GalacticCenterRgilbrand,
            Ayanamsa::GalacticEquatorIau1958,
            Ayanamsa::GalacticEquatorTrue,
            Ayanamsa::GalacticEquatorMula,
            Ayanamsa::GalacticCenterMardyks,
            Ayanamsa::GalacticCenterMulaWilhelm,
            Ayanamsa::GalacticCenterCochrane,
            Ayanamsa::GalacticEquatorFiorenza,
        ] {
            assert!(
                galactic_offset_degrees(&m, jd).is_some(),
                "{m:?} in-window should be Some"
            );
            assert!(
                galactic_offset_degrees(&m, 2_300_000.0).is_none(),
                "{m:?} pre-window should be None"
            );
        }
        assert!(galactic_offset_degrees(&Ayanamsa::Lahiri, jd).is_none());
    }
}
