//! Committed cubic polynomials for the true-star ayanamsa modes (True Chitra /
//! True Citra), fit by `tools/se-ayanamsa-reference fit` to the Swiss Ephemeris
//! **mean** ayanamsa (iflag = SEFLG_NONUT | SEFLG_NOABERR) over 1900–2100. The
//! mean ayanamsa drops apparent-place periodicity (nutation, annual aberration),
//! so it is smooth and cubic-fittable to sub-arcsecond accuracy.
//! ayanamsa_deg(T) = c0 + c1 T + c2 T^2 + c3 T^3, T = (jd-2451545)/36525.
#![forbid(unsafe_code)]

use pleiades_types::Ayanamsa;

/// True-star cubic fit window (1900-01-01 .. ~2100), JD TT. Outside this the
/// committed polynomial extrapolates to unreliable values, so we fail closed
/// rather than return a silently-wrong sidereal offset (the gate validates only
/// in-window; see the audit record).
pub(crate) const TRUE_STAR_FIT_JD_MIN: f64 = 2_415_020.0;
pub(crate) const TRUE_STAR_FIT_JD_MAX: f64 = 2_488_070.0;

// Generated by se-ayanamsa-reference fit — paste the printed lines here.
pub(crate) const TRUECHITRA_COEFFS: [f64; 4] = [
    2.384136130097e1,
    1.395701001342e0,
    3.073537211274e-4,
    3.543863063632e-8,
];
pub(crate) const TRUECITRA_COEFFS: [f64; 4] = [
    2.384136130097e1,
    1.395701001342e0,
    3.073537211274e-4,
    3.543863063632e-8,
];
pub(crate) const TRUEREVATI_COEFFS: [f64; 4] = [
    2.004421150102e1,
    1.400078122255e0,
    3.068214535854e-4,
    2.803233874782e-8,
];
pub(crate) const TRUEPUSHYA_COEFFS: [f64; 4] = [
    2.272199523390e1,
    1.398093989666e0,
    3.067347395306e-4,
    2.874774824886e-8,
];
pub(crate) const TRUEMULA_COEFFS: [f64; 4] = [
    2.458570826164e1,
    1.396669414545e0,
    3.204632064232e-4,
    3.060838144777e-8,
];
pub(crate) const TRUESHEORAN_COEFFS: [f64; 4] = [
    2.522935301765e1,
    1.398093989666e0,
    3.067347394697e-4,
    2.874769163152e-8,
];

pub(crate) fn eval(coeffs: &[f64; 4], jd_tt: f64) -> f64 {
    let t = (jd_tt - 2_451_545.0) / 36_525.0;
    coeffs[0] + coeffs[1] * t + coeffs[2] * t * t + coeffs[3] * t * t * t
}

/// Returns the true-star sidereal offset in degrees, or `None` if the mode is
/// not a committed true-star mode, or if `jd_tt` is outside the polynomial fit
/// window (`TRUE_STAR_FIT_JD_MIN ..= TRUE_STAR_FIT_JD_MAX`). Outside the window
/// the cubic extrapolates to unreliable values, so we fail closed rather than
/// silently return a wrong offset.
pub(crate) fn true_star_offset_degrees(ayanamsa: &Ayanamsa, jd_tt: f64) -> Option<f64> {
    match ayanamsa {
        Ayanamsa::TrueChitra
        | Ayanamsa::TrueCitra
        | Ayanamsa::TrueRevati
        | Ayanamsa::TruePushya
        | Ayanamsa::TrueMula
        | Ayanamsa::TrueSheoran => {
            if !(TRUE_STAR_FIT_JD_MIN..=TRUE_STAR_FIT_JD_MAX).contains(&jd_tt) {
                return None;
            }
            let coeffs = match ayanamsa {
                Ayanamsa::TrueChitra => &TRUECHITRA_COEFFS,
                Ayanamsa::TrueCitra => &TRUECITRA_COEFFS,
                Ayanamsa::TrueRevati => &TRUEREVATI_COEFFS,
                Ayanamsa::TruePushya => &TRUEPUSHYA_COEFFS,
                Ayanamsa::TrueMula => &TRUEMULA_COEFFS,
                _ => &TRUESHEORAN_COEFFS,
            };
            Some(eval(coeffs, jd_tt))
        }
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn in_window_j2000_returns_some_for_true_star_modes() {
        let jd = 2_451_545.0; // J2000
        assert!(
            true_star_offset_degrees(&Ayanamsa::TrueChitra, jd).is_some(),
            "TrueChitra at J2000 should return Some"
        );
        assert!(
            true_star_offset_degrees(&Ayanamsa::TrueCitra, jd).is_some(),
            "TrueCitra at J2000 should return Some"
        );
    }

    #[test]
    fn out_of_window_jd_returns_none_for_true_star_modes() {
        // Before fit window
        let jd_early = 2_300_000.0;
        assert!(
            true_star_offset_degrees(&Ayanamsa::TrueChitra, jd_early).is_none(),
            "TrueChitra before fit window should return None"
        );
        assert!(
            true_star_offset_degrees(&Ayanamsa::TrueCitra, jd_early).is_none(),
            "TrueCitra before fit window should return None"
        );
        // After fit window
        let jd_late = 2_600_000.0;
        assert!(
            true_star_offset_degrees(&Ayanamsa::TrueChitra, jd_late).is_none(),
            "TrueChitra after fit window should return None"
        );
        assert!(
            true_star_offset_degrees(&Ayanamsa::TrueCitra, jd_late).is_none(),
            "TrueCitra after fit window should return None"
        );
    }

    #[test]
    fn boundary_jds_return_some_inclusive() {
        // Lower boundary
        assert!(
            true_star_offset_degrees(&Ayanamsa::TrueChitra, TRUE_STAR_FIT_JD_MIN).is_some(),
            "TrueChitra at lower boundary should return Some (inclusive)"
        );
        assert!(
            true_star_offset_degrees(&Ayanamsa::TrueCitra, TRUE_STAR_FIT_JD_MIN).is_some(),
            "TrueCitra at lower boundary should return Some (inclusive)"
        );
        // Upper boundary
        assert!(
            true_star_offset_degrees(&Ayanamsa::TrueChitra, TRUE_STAR_FIT_JD_MAX).is_some(),
            "TrueChitra at upper boundary should return Some (inclusive)"
        );
        assert!(
            true_star_offset_degrees(&Ayanamsa::TrueCitra, TRUE_STAR_FIT_JD_MAX).is_some(),
            "TrueCitra at upper boundary should return Some (inclusive)"
        );
    }

    #[test]
    fn new_true_star_modes_return_some_in_window() {
        let jd = 2_451_545.0;
        for m in [
            Ayanamsa::TrueRevati,
            Ayanamsa::TruePushya,
            Ayanamsa::TrueMula,
            Ayanamsa::TrueSheoran,
        ] {
            assert!(
                true_star_offset_degrees(&m, jd).is_some(),
                "{m:?} in-window should be Some"
            );
            assert!(
                true_star_offset_degrees(&m, 2_300_000.0).is_none(),
                "{m:?} pre-window should be None"
            );
        }
    }

    #[test]
    fn non_true_star_modes_always_return_none() {
        // Non-true-star modes are not window-bounded — they simply return None always.
        let jd = 2_451_545.0;
        assert!(true_star_offset_degrees(&Ayanamsa::Lahiri, jd).is_none());
        assert!(true_star_offset_degrees(&Ayanamsa::Raman, jd).is_none());
    }
}
