//! Committed cubic polynomials for the true-star ayanamsa modes (True Chitra /
//! True Citra), fit by `tools/se-ayanamsa-reference fit` to the Swiss Ephemeris
//! **mean** ayanamsa (iflag = SEFLG_NONUT | SEFLG_NOABERR) over 1900–2100. The
//! mean ayanamsa drops apparent-place periodicity (nutation, annual aberration),
//! so it is smooth and cubic-fittable to sub-arcsecond accuracy.
//! ayanamsa_deg(T) = c0 + c1 T + c2 T^2 + c3 T^3, T = (jd-2451545)/36525.
#![forbid(unsafe_code)]

use pleiades_types::Ayanamsa;

// Generated by se-ayanamsa-reference fit — paste the two printed lines here.
pub(crate) const TRUECHITRA_COEFFS: [f64; 4] = [2.384136130097e1, 1.395701001342e0, 3.073537211274e-4, 3.543863063632e-8];
pub(crate) const TRUECITRA_COEFFS: [f64; 4] = [2.384136130097e1, 1.395701001342e0, 3.073537211274e-4, 3.543863063632e-8];

fn eval(coeffs: &[f64; 4], jd_tt: f64) -> f64 {
    let t = (jd_tt - 2_451_545.0) / 36_525.0;
    coeffs[0] + coeffs[1] * t + coeffs[2] * t * t + coeffs[3] * t * t * t
}

/// Returns the true-star sidereal offset in degrees, or `None` if the mode is
/// not a committed true-star mode.
pub(crate) fn true_star_offset_degrees(ayanamsa: &Ayanamsa, jd_tt: f64) -> Option<f64> {
    match ayanamsa {
        Ayanamsa::TrueChitra => Some(eval(&TRUECHITRA_COEFFS, jd_tt)),
        Ayanamsa::TrueCitra => Some(eval(&TRUECITRA_COEFFS, jd_tt)),
        _ => None,
    }
}
