[package]
name = "pleiades-apsides"
description = "Lunar orbit points (mean and osculating nodes and apsides) for the pleiades astrology workspace"
version = "0.5.4"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"

[dependencies]
[dev-dependencies]
proptest = { workspace = true }
