use libswisseph_sys::raw::swe_set_sid_mode;
use swisseph::swe::get_ayanamsa;

/// (pleiades mode_code, SE sidereal-mode integer)
const MODES: &[(&str, i32)] = &[
    ("FaganBradley",  0),
    ("Lahiri",        1),
    ("Raman",         3),
    ("Krishnamurti",  5),
    ("TrueChitra",   27),
    ("TrueCitra",    27),
];

/// Hold-out validation instants (jd_tt). Deliberately NOT on the dense fit grid
/// (Task: fit uses an even-year grid), so the gate is a genuine hold-out check.
const HOLDOUT_JD_TT: &[f64] = &[
    2_415_020.5,   // 1900-01-01
    2_420_000.5,
    2_424_152.0,   // ~1925
    2_429_000.5,
    2_433_282.5,   // ~1950
    2_438_000.5,
    2_451_545.0,   // J2000.0
    2_460_676.5,   // ~2025
    2_469_807.0,   // ~2050
    2_488_070.0,   // ~2100
];

fn ayanamsa(code: i32, jd_tt: f64) -> f64 {
    unsafe { swe_set_sid_mode(code, 0.0, 0.0); }
    let v = get_ayanamsa(jd_tt);
    assert!(v.is_finite(), "SE returned non-finite ayanamsa for code {code} at jd {jd_tt}");
    v
}

fn emit_corpus() {
    println!("mode_code,jd_tt,se_ayanamsa_deg");
    for &(name, code) in MODES {
        for &jd in HOLDOUT_JD_TT {
            println!("{name},{jd},{:.9}", ayanamsa(code, jd));
        }
    }
}

/// Solve a small symmetric normal-equation system by Gaussian elimination.
fn solve(mut a: Vec<Vec<f64>>, mut b: Vec<f64>) -> Vec<f64> {
    let n = b.len();
    for col in 0..n {
        let mut piv = col;
        for r in col + 1..n { if a[r][col].abs() > a[piv][col].abs() { piv = r; } }
        a.swap(col, piv); b.swap(col, piv);
        let d = a[col][col];
        for r in 0..n {
            if r == col { continue; }
            let f = a[r][col] / d;
            for c in col..n { a[r][c] -= f * a[col][c]; }
            b[r] -= f * b[col];
        }
    }
    (0..n).map(|i| b[i] / a[i][i]).collect()
}

/// Fit ayanamsa_deg(T) = c0 + c1 T + c2 T^2 + c3 T^3, T = (jd-2451545)/36525,
/// over a dense even-year grid, and print a Rust const block.
fn emit_fit() {
    let dense: Vec<f64> = (1900..=2100).step_by(2)
        .map(|y| 2_451_545.0 + (y as f64 - 2000.0) * 365.25)
        .collect();
    println!("// Generated by se-ayanamsa-reference fit. T = (jd_tt - 2451545.0)/36525.0");
    for &(name, code) in &[("TrueChitra", 27), ("TrueCitra", 27)] {
        // Normal equations for a degree-3 polynomial.
        let mut ata = vec![vec![0.0f64; 4]; 4];
        let mut atb = vec![0.0f64; 4];
        for &jd in &dense {
            let t = (jd - 2_451_545.0) / 36_525.0;
            let powers = [1.0, t, t * t, t * t * t];
            let y = ayanamsa(code, jd);
            for i in 0..4 {
                atb[i] += powers[i] * y;
                for j in 0..4 { ata[i][j] += powers[i] * powers[j]; }
            }
        }
        let c = solve(ata, atb);
        println!(
            "pub(crate) const {}_COEFFS: [f64; 4] = [{:.12e}, {:.12e}, {:.12e}, {:.12e}];",
            name.to_uppercase(), c[0], c[1], c[2], c[3]
        );
    }
}

fn main() {
    match std::env::args().nth(1).as_deref() {
        Some("fit") => emit_fit(),
        _ => emit_corpus(),
    }
}
