//! Comparison report type, backend comparison, and report rendering.

use std::fmt;

use crate::*;

/// A comparison report generated by the validation tooling.
#[derive(Clone, Debug)]
pub struct ComparisonReport {
    /// Corpus name.
    pub corpus_name: String,
    /// Corpus summary, including its epoch range and body coverage.
    pub corpus_summary: CorpusSummary,
    /// Apparentness mode used by the corpus.
    pub apparentness: Apparentness,
    /// Metadata for the reference backend.
    pub reference_backend: BackendMetadata,
    /// Metadata for the candidate backend.
    pub candidate_backend: BackendMetadata,
    /// Per-body comparison samples.
    pub samples: Vec<ComparisonSample>,
    /// Aggregate statistics.
    pub summary: ComparisonSummary,
}
/// Creates the default reference backend.
pub fn default_reference_backend() -> JplSnapshotBackend {
    JplSnapshotBackend::new()
}

/// Creates the default candidate backend.
pub fn default_candidate_backend() -> CompositeBackend<Vsop87Backend, ElpBackend> {
    CompositeBackend::new(Vsop87Backend::new(), ElpBackend::new())
}

/// Compares two backends across the supplied corpus.
pub fn compare_backends(
    reference: &dyn EphemerisBackend,
    candidate: &dyn EphemerisBackend,
    corpus: &ValidationCorpus,
) -> Result<ComparisonReport, EphemerisError> {
    let mut samples = Vec::with_capacity(corpus.requests.len());
    let mut summary = ComparisonSummary::default();
    let mut distance_sum = 0.0;
    let mut distance_sum_sq = 0.0;
    let mut distance_count = 0usize;

    for request in &corpus.requests {
        let reference_result = extract_ecliptic(reference.position(request)?)?;
        let candidate_result = extract_ecliptic(candidate.position(request)?)?;
        let longitude_delta_deg =
            angular_delta(reference_result.longitude, candidate_result.longitude);
        let latitude_delta_deg =
            (reference_result.latitude.degrees() - candidate_result.latitude.degrees()).abs();
        let distance_delta_au = match (reference_result.distance_au, candidate_result.distance_au) {
            (Some(reference), Some(candidate)) => Some((reference - candidate).abs()),
            _ => None,
        };

        if let Some(delta) = distance_delta_au {
            distance_sum += delta;
            distance_sum_sq += delta * delta;
            distance_count += 1;
            match summary.max_distance_delta_au {
                Some(current) if delta < current => {}
                _ => {
                    summary.max_distance_delta_au = Some(delta);
                    summary.max_distance_delta_body = Some(request.body.clone());
                }
            }
        }

        summary.sample_count += 1;
        if longitude_delta_deg >= summary.max_longitude_delta_deg {
            summary.max_longitude_delta_deg = longitude_delta_deg;
            summary.max_longitude_delta_body = Some(request.body.clone());
        }
        summary.mean_longitude_delta_deg += longitude_delta_deg;
        if latitude_delta_deg >= summary.max_latitude_delta_deg {
            summary.max_latitude_delta_deg = latitude_delta_deg;
            summary.max_latitude_delta_body = Some(request.body.clone());
        }
        summary.mean_latitude_delta_deg += latitude_delta_deg;

        samples.push(ComparisonSample {
            body: request.body.clone(),
            reference: reference_result,
            candidate: candidate_result,
            longitude_delta_deg,
            latitude_delta_deg,
            distance_delta_au,
        });
    }

    if summary.sample_count > 0 {
        let sample_count = summary.sample_count as f64;
        summary.mean_longitude_delta_deg /= sample_count;
        summary.rms_longitude_delta_deg = (samples
            .iter()
            .map(|sample| sample.longitude_delta_deg * sample.longitude_delta_deg)
            .sum::<f64>()
            / sample_count)
            .sqrt();
        summary.mean_latitude_delta_deg /= sample_count;
        summary.rms_latitude_delta_deg = (samples
            .iter()
            .map(|sample| sample.latitude_delta_deg * sample.latitude_delta_deg)
            .sum::<f64>()
            / sample_count)
            .sqrt();
    }
    if distance_count > 0 {
        summary.mean_distance_delta_au = Some(distance_sum / distance_count as f64);
        summary.rms_distance_delta_au = Some((distance_sum_sq / distance_count as f64).sqrt());
    }

    Ok(ComparisonReport {
        corpus_name: corpus.name.clone(),
        corpus_summary: corpus.summary(),
        apparentness: corpus.apparentness,
        reference_backend: reference.metadata(),
        candidate_backend: candidate.metadata(),
        samples,
        summary,
    })
}
impl fmt::Display for ComparisonReport {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        writeln!(f, "Comparison report")?;
        writeln!(f, "Comparison corpus")?;
        write_corpus_summary(f, &self.corpus_summary)?;
        writeln!(
            f,
            "  release-grade guard: {}",
            match validated_comparison_corpus_release_guard_summary_for_report() {
                Ok(summary) => summary,
                Err(_) => return Err(fmt::Error),
            }
        )?;
        writeln!(f)?;
        writeln!(f, "Reference backend: {}", self.reference_backend.id)?;
        writeln!(f, "Candidate backend: {}", self.candidate_backend.id)?;
        writeln!(f)?;
        write_comparison_summary(f, self)?;
        writeln!(f)?;
        write_body_comparison_summaries(f, &self.body_summaries())?;
        writeln!(f)?;
        write_body_class_envelopes(f, &self.samples)?;
        writeln!(f)?;
        write_body_class_tolerance_posture(f, &self.samples, &self.candidate_backend.family)?;
        writeln!(f)?;
        write_tolerance_summaries(f, &self.tolerance_summaries())?;
        writeln!(f)?;
        write_regression_section(f, "Notable regressions", &self.notable_regressions())?;
        writeln!(f)?;
        writeln!(f, "Samples")?;
        for sample in &self.samples {
            writeln!(
                f,
                "  {}: Δlon={:.12}°, Δlat={:.12}°, Δdist={}",
                sample.body,
                sample.longitude_delta_deg,
                sample.latitude_delta_deg,
                sample
                    .distance_delta_au
                    .map(|value| format!("{value:.12} AU"))
                    .unwrap_or_else(|| "n/a".to_string())
            )?;
        }
        Ok(())
    }
}

impl ComparisonReport {
    /// Returns the structured comparison-audit summary used by compact report surfaces.
    pub fn comparison_audit_summary(&self) -> ComparisonAuditSummary {
        comparison_audit_summary(self)
    }

    /// Returns per-body comparison statistics preserving first-seen body order.
    pub fn body_summaries(&self) -> Vec<BodyComparisonSummary> {
        body_comparison_summaries(&self.samples)
    }

    /// Returns per-body-class comparison envelopes preserving first-seen class order.
    pub(crate) fn body_class_summaries(&self) -> Vec<BodyClassSummary> {
        body_class_summaries(&self.samples)
    }

    /// Returns per-body tolerance status preserving first-seen body order.
    pub fn tolerance_summaries(&self) -> Vec<BodyToleranceSummary> {
        let candidate_family = &self.candidate_backend.family;
        self.body_summaries()
            .into_iter()
            .map(|summary| body_tolerance_summary(summary, candidate_family))
            .collect()
    }

    /// Returns the expected tolerance catalog for the candidate backend family.
    pub fn tolerance_policy_entries(&self) -> Vec<ComparisonToleranceEntry> {
        comparison_tolerance_policy_entries(&self.candidate_backend.family)
    }

    /// Returns the structured tolerance policy summary for the candidate backend family.
    pub fn tolerance_policy_summary(&self) -> ComparisonTolerancePolicySummary {
        comparison_tolerance_policy_summary_details(self)
    }

    /// Returns per-body-class tolerance posture preserving first-seen class order.
    pub(crate) fn body_class_tolerance_summaries(&self) -> Vec<BodyClassToleranceSummary> {
        body_class_tolerance_summaries(&self.samples, &self.candidate_backend.family)
    }

    /// Returns the samples that exceed the built-in regression thresholds.
    pub fn notable_regressions(&self) -> Vec<RegressionFinding> {
        self.samples
            .iter()
            .filter_map(|sample| regression_finding(sample, &self.candidate_backend.family))
            .collect()
    }

    /// Returns a preserved archive of the current regression findings.
    pub fn regression_archive(&self) -> RegressionArchive {
        RegressionArchive {
            corpus_name: self.corpus_name.clone(),
            cases: self.notable_regressions(),
        }
    }
}

fn extract_ecliptic(result: EphemerisResult) -> Result<EclipticCoordinates, EphemerisError> {
    result.ecliptic.ok_or_else(|| {
        EphemerisError::new(
            EphemerisErrorKind::InvalidRequest,
            "backend did not return ecliptic coordinates for the validation corpus",
        )
    })
}

fn angular_delta(reference: Longitude, candidate: Longitude) -> f64 {
    (pleiades_core::Angle::from_degrees(reference.degrees() - candidate.degrees())
        .normalized_signed()
        .degrees())
    .abs()
}

#[derive(Clone, Debug)]
struct BodyComparisonAccumulator {
    body: CelestialBody,
    sample_count: usize,
    longitude_sum_deg: f64,
    longitude_sum_sq_deg: f64,
    latitude_sum_deg: f64,
    latitude_sum_sq_deg: f64,
    distance_sum_au: f64,
    distance_sum_sq_au: f64,
    distance_count: usize,
    max_longitude_delta_deg: f64,
    max_longitude_delta_body: Option<CelestialBody>,
    max_latitude_delta_deg: f64,
    max_latitude_delta_body: Option<CelestialBody>,
    max_distance_delta_au: Option<f64>,
    max_distance_delta_body: Option<CelestialBody>,
}

impl BodyComparisonAccumulator {
    fn new(body: CelestialBody) -> Self {
        Self {
            body,
            sample_count: 0,
            longitude_sum_deg: 0.0,
            longitude_sum_sq_deg: 0.0,
            latitude_sum_deg: 0.0,
            latitude_sum_sq_deg: 0.0,
            distance_sum_au: 0.0,
            distance_sum_sq_au: 0.0,
            distance_count: 0,
            max_longitude_delta_deg: 0.0,
            max_longitude_delta_body: None,
            max_latitude_delta_deg: 0.0,
            max_latitude_delta_body: None,
            max_distance_delta_au: None,
            max_distance_delta_body: None,
        }
    }

    fn push(&mut self, sample: &ComparisonSample) {
        self.sample_count += 1;
        self.longitude_sum_deg += sample.longitude_delta_deg;
        self.longitude_sum_sq_deg += sample.longitude_delta_deg * sample.longitude_delta_deg;
        if sample.longitude_delta_deg >= self.max_longitude_delta_deg {
            self.max_longitude_delta_deg = sample.longitude_delta_deg;
            self.max_longitude_delta_body = Some(sample.body.clone());
        }
        self.latitude_sum_deg += sample.latitude_delta_deg;
        self.latitude_sum_sq_deg += sample.latitude_delta_deg * sample.latitude_delta_deg;
        if sample.latitude_delta_deg >= self.max_latitude_delta_deg {
            self.max_latitude_delta_deg = sample.latitude_delta_deg;
            self.max_latitude_delta_body = Some(sample.body.clone());
        }
        if let Some(delta) = sample.distance_delta_au {
            self.distance_sum_au += delta;
            self.distance_sum_sq_au += delta * delta;
            self.distance_count += 1;
            match self.max_distance_delta_au {
                Some(current) if delta < current => {}
                _ => {
                    self.max_distance_delta_au = Some(delta);
                    self.max_distance_delta_body = Some(sample.body.clone());
                }
            }
        }
    }

    fn finish(self) -> BodyComparisonSummary {
        let sample_count = self.sample_count as f64;
        BodyComparisonSummary {
            body: self.body,
            sample_count: self.sample_count,
            max_longitude_delta_body: self.max_longitude_delta_body,
            max_longitude_delta_deg: self.max_longitude_delta_deg,
            mean_longitude_delta_deg: if self.sample_count > 0 {
                self.longitude_sum_deg / sample_count
            } else {
                0.0
            },
            rms_longitude_delta_deg: if self.sample_count > 0 {
                (self.longitude_sum_sq_deg / sample_count).sqrt()
            } else {
                0.0
            },
            max_latitude_delta_body: self.max_latitude_delta_body,
            max_latitude_delta_deg: self.max_latitude_delta_deg,
            mean_latitude_delta_deg: if self.sample_count > 0 {
                self.latitude_sum_deg / sample_count
            } else {
                0.0
            },
            rms_latitude_delta_deg: if self.sample_count > 0 {
                (self.latitude_sum_sq_deg / sample_count).sqrt()
            } else {
                0.0
            },
            max_distance_delta_body: self.max_distance_delta_body,
            max_distance_delta_au: self.max_distance_delta_au,
            mean_distance_delta_au: if self.distance_count > 0 {
                Some(self.distance_sum_au / self.distance_count as f64)
            } else {
                None
            },
            rms_distance_delta_au: if self.distance_count > 0 {
                Some((self.distance_sum_sq_au / self.distance_count as f64).sqrt())
            } else {
                None
            },
        }
    }
}

fn body_comparison_summaries(samples: &[ComparisonSample]) -> Vec<BodyComparisonSummary> {
    let mut accumulators: Vec<BodyComparisonAccumulator> = Vec::new();

    for sample in samples {
        if let Some(accumulator) = accumulators
            .iter_mut()
            .find(|accumulator| accumulator.body == sample.body)
        {
            accumulator.push(sample);
        } else {
            let mut accumulator = BodyComparisonAccumulator::new(sample.body.clone());
            accumulator.push(sample);
            accumulators.push(accumulator);
        }
    }

    accumulators
        .into_iter()
        .map(BodyComparisonAccumulator::finish)
        .collect()
}

#[derive(Clone, Debug)]
struct BodyClassAccumulator {
    class: BodyClass,
    sample_count: usize,
    longitude_sum_deg: f64,
    longitude_sum_sq_deg: f64,
    longitude_values: Vec<f64>,
    latitude_sum_deg: f64,
    latitude_sum_sq_deg: f64,
    latitude_values: Vec<f64>,
    distance_sum_au: f64,
    distance_sum_sq_au: f64,
    distance_values: Vec<f64>,
    distance_count: usize,
    max_longitude_delta_deg: f64,
    max_longitude_delta_body: Option<CelestialBody>,
    max_latitude_delta_deg: f64,
    max_latitude_delta_body: Option<CelestialBody>,
    max_distance_delta_au: Option<f64>,
    max_distance_delta_body: Option<CelestialBody>,
}

impl BodyClassAccumulator {
    fn new(class: BodyClass) -> Self {
        Self {
            class,
            sample_count: 0,
            longitude_sum_deg: 0.0,
            longitude_sum_sq_deg: 0.0,
            longitude_values: Vec::new(),
            latitude_sum_deg: 0.0,
            latitude_sum_sq_deg: 0.0,
            latitude_values: Vec::new(),
            distance_sum_au: 0.0,
            distance_sum_sq_au: 0.0,
            distance_values: Vec::new(),
            distance_count: 0,
            max_longitude_delta_deg: 0.0,
            max_longitude_delta_body: None,
            max_latitude_delta_deg: 0.0,
            max_latitude_delta_body: None,
            max_distance_delta_au: None,
            max_distance_delta_body: None,
        }
    }

    fn push(&mut self, sample: &ComparisonSample) {
        self.sample_count += 1;
        self.longitude_sum_deg += sample.longitude_delta_deg;
        self.longitude_sum_sq_deg += sample.longitude_delta_deg * sample.longitude_delta_deg;
        self.longitude_values.push(sample.longitude_delta_deg);
        if sample.longitude_delta_deg >= self.max_longitude_delta_deg {
            self.max_longitude_delta_deg = sample.longitude_delta_deg;
            self.max_longitude_delta_body = Some(sample.body.clone());
        }
        self.latitude_sum_deg += sample.latitude_delta_deg;
        self.latitude_sum_sq_deg += sample.latitude_delta_deg * sample.latitude_delta_deg;
        self.latitude_values.push(sample.latitude_delta_deg);
        if sample.latitude_delta_deg >= self.max_latitude_delta_deg {
            self.max_latitude_delta_deg = sample.latitude_delta_deg;
            self.max_latitude_delta_body = Some(sample.body.clone());
        }
        if let Some(delta) = sample.distance_delta_au {
            self.distance_sum_au += delta;
            self.distance_sum_sq_au += delta * delta;
            self.distance_values.push(delta);
            self.distance_count += 1;
            match self.max_distance_delta_au {
                Some(current) if delta < current => {}
                _ => {
                    self.max_distance_delta_au = Some(delta);
                    self.max_distance_delta_body = Some(sample.body.clone());
                }
            }
        }
    }

    fn finish(self) -> BodyClassSummary {
        let mut longitude_values = self.longitude_values;
        let mut latitude_values = self.latitude_values;
        let mut distance_values = self.distance_values;
        BodyClassSummary {
            class: self.class,
            sample_count: self.sample_count,
            max_longitude_delta_body: self.max_longitude_delta_body,
            max_longitude_delta_deg: self.max_longitude_delta_deg,
            sum_longitude_delta_deg: self.longitude_sum_deg,
            sum_longitude_delta_sq_deg: self.longitude_sum_sq_deg,
            median_longitude_delta_deg: median_value(&mut longitude_values).unwrap_or_default(),
            percentile_longitude_delta_deg: percentile_value(&mut longitude_values, 0.95)
                .unwrap_or_default(),
            max_latitude_delta_body: self.max_latitude_delta_body,
            max_latitude_delta_deg: self.max_latitude_delta_deg,
            sum_latitude_delta_deg: self.latitude_sum_deg,
            sum_latitude_delta_sq_deg: self.latitude_sum_sq_deg,
            median_latitude_delta_deg: median_value(&mut latitude_values).unwrap_or_default(),
            percentile_latitude_delta_deg: percentile_value(&mut latitude_values, 0.95)
                .unwrap_or_default(),
            max_distance_delta_body: self.max_distance_delta_body,
            max_distance_delta_au: self.max_distance_delta_au,
            sum_distance_delta_au: self.distance_sum_au,
            sum_distance_delta_sq_au: self.distance_sum_sq_au,
            distance_count: self.distance_count,
            median_distance_delta_au: median_value(&mut distance_values),
            percentile_distance_delta_au: percentile_value(&mut distance_values, 0.95),
        }
    }
}

pub(crate) fn body_class_summaries(samples: &[ComparisonSample]) -> Vec<BodyClassSummary> {
    let mut accumulators = BodyClass::ALL.map(BodyClassAccumulator::new);

    for sample in samples {
        accumulators[body_class(&sample.body).index()].push(sample);
    }

    accumulators
        .into_iter()
        .filter(|summary| summary.sample_count > 0)
        .map(BodyClassAccumulator::finish)
        .collect()
}

#[derive(Clone, Debug)]
struct BodyClassToleranceAccumulator {
    class: BodyClass,
    backend_family: BackendFamily,
    body_count: usize,
    sample_count: usize,
    sum_longitude_delta_deg: f64,
    sum_longitude_delta_sq_deg: f64,
    longitude_values: Vec<f64>,
    sum_latitude_delta_deg: f64,
    sum_latitude_delta_sq_deg: f64,
    latitude_values: Vec<f64>,
    sum_distance_delta_au: f64,
    sum_distance_delta_sq_au: f64,
    distance_values: Vec<f64>,
    distance_count: usize,
    within_tolerance_body_count: usize,
    outside_tolerance_body_count: usize,
    outside_tolerance_sample_count: usize,
    max_longitude_delta_body: Option<CelestialBody>,
    max_longitude_delta_deg: Option<f64>,
    max_latitude_delta_body: Option<CelestialBody>,
    max_latitude_delta_deg: Option<f64>,
    max_distance_delta_body: Option<CelestialBody>,
    max_distance_delta_au: Option<f64>,
    outside_bodies: Vec<CelestialBody>,
}

impl BodyClassToleranceAccumulator {
    fn new(class: BodyClass, backend_family: BackendFamily) -> Self {
        Self {
            class,
            backend_family,
            body_count: 0,
            sample_count: 0,
            sum_longitude_delta_deg: 0.0,
            sum_longitude_delta_sq_deg: 0.0,
            longitude_values: Vec::new(),
            sum_latitude_delta_deg: 0.0,
            sum_latitude_delta_sq_deg: 0.0,
            latitude_values: Vec::new(),
            sum_distance_delta_au: 0.0,
            sum_distance_delta_sq_au: 0.0,
            distance_values: Vec::new(),
            distance_count: 0,
            within_tolerance_body_count: 0,
            outside_tolerance_body_count: 0,
            outside_tolerance_sample_count: 0,
            max_longitude_delta_body: None,
            max_longitude_delta_deg: None,
            max_latitude_delta_body: None,
            max_latitude_delta_deg: None,
            max_distance_delta_body: None,
            max_distance_delta_au: None,
            outside_bodies: Vec::new(),
        }
    }

    fn push_sample(&mut self, sample: &ComparisonSample) {
        self.sample_count += 1;
        self.sum_longitude_delta_deg += sample.longitude_delta_deg;
        self.sum_longitude_delta_sq_deg += sample.longitude_delta_deg * sample.longitude_delta_deg;
        self.longitude_values.push(sample.longitude_delta_deg);
        match self.max_longitude_delta_deg {
            Some(current) if sample.longitude_delta_deg < current => {}
            _ => {
                self.max_longitude_delta_deg = Some(sample.longitude_delta_deg);
                self.max_longitude_delta_body = Some(sample.body.clone());
            }
        }
        self.sum_latitude_delta_deg += sample.latitude_delta_deg;
        self.sum_latitude_delta_sq_deg += sample.latitude_delta_deg * sample.latitude_delta_deg;
        self.latitude_values.push(sample.latitude_delta_deg);
        match self.max_latitude_delta_deg {
            Some(current) if sample.latitude_delta_deg < current => {}
            _ => {
                self.max_latitude_delta_deg = Some(sample.latitude_delta_deg);
                self.max_latitude_delta_body = Some(sample.body.clone());
            }
        }
        if let Some(delta) = sample.distance_delta_au {
            self.sum_distance_delta_au += delta;
            self.sum_distance_delta_sq_au += delta * delta;
            self.distance_values.push(delta);
            self.distance_count += 1;
            match self.max_distance_delta_au {
                Some(current) if delta < current => {}
                _ => {
                    self.max_distance_delta_au = Some(delta);
                    self.max_distance_delta_body = Some(sample.body.clone());
                }
            }
        }

        let tolerance = comparison_tolerance_for_class(self.class, &self.backend_family);
        let distance_within = match (sample.distance_delta_au, tolerance.max_distance_delta_au) {
            (Some(measured), Some(limit)) => measured <= limit,
            (None, _) | (_, None) => true,
        };
        if sample.longitude_delta_deg > tolerance.max_longitude_delta_deg
            || sample.latitude_delta_deg > tolerance.max_latitude_delta_deg
            || !distance_within
        {
            self.outside_tolerance_sample_count += 1;
        }
    }

    fn push_tolerance(&mut self, summary: &BodyToleranceSummary) {
        self.body_count += 1;
        if summary.within_tolerance {
            self.within_tolerance_body_count += 1;
        } else {
            self.outside_tolerance_body_count += 1;
            self.outside_bodies.push(summary.body.clone());
        }
    }

    fn finish(self) -> BodyClassToleranceSummary {
        let mut longitude_values = self.longitude_values;
        let mut latitude_values = self.latitude_values;
        let mut distance_values = self.distance_values;
        BodyClassToleranceSummary {
            class: self.class,
            tolerance: comparison_tolerance_for_class(self.class, &self.backend_family),
            body_count: self.body_count,
            sample_count: self.sample_count,
            within_tolerance_body_count: self.within_tolerance_body_count,
            outside_tolerance_body_count: self.outside_tolerance_body_count,
            outside_tolerance_sample_count: self.outside_tolerance_sample_count,
            max_longitude_delta_body: self.max_longitude_delta_body,
            max_longitude_delta_deg: self.max_longitude_delta_deg,
            max_latitude_delta_body: self.max_latitude_delta_body,
            max_latitude_delta_deg: self.max_latitude_delta_deg,
            max_distance_delta_body: self.max_distance_delta_body,
            max_distance_delta_au: self.max_distance_delta_au,
            sum_longitude_delta_deg: self.sum_longitude_delta_deg,
            sum_longitude_delta_sq_deg: self.sum_longitude_delta_sq_deg,
            sum_latitude_delta_deg: self.sum_latitude_delta_deg,
            sum_latitude_delta_sq_deg: self.sum_latitude_delta_sq_deg,
            sum_distance_delta_au: self.sum_distance_delta_au,
            sum_distance_delta_sq_au: self.sum_distance_delta_sq_au,
            distance_count: self.distance_count,
            median_longitude_delta_deg: median_value(&mut longitude_values).unwrap_or_default(),
            percentile_longitude_delta_deg: percentile_value(&mut longitude_values, 0.95)
                .unwrap_or_default(),
            median_latitude_delta_deg: median_value(&mut latitude_values).unwrap_or_default(),
            percentile_latitude_delta_deg: percentile_value(&mut latitude_values, 0.95)
                .unwrap_or_default(),
            median_distance_delta_au: median_value(&mut distance_values),
            percentile_distance_delta_au: percentile_value(&mut distance_values, 0.95),
            outside_bodies: self.outside_bodies,
        }
    }
}

pub(crate) fn body_class_tolerance_summaries(
    samples: &[ComparisonSample],
    backend_family: &BackendFamily,
) -> Vec<BodyClassToleranceSummary> {
    let body_summaries = body_comparison_summaries(samples);
    let mut accumulators = BodyClass::ALL
        .map(|class| BodyClassToleranceAccumulator::new(class, backend_family.clone()));

    for sample in samples {
        accumulators[body_class(&sample.body).index()].push_sample(sample);
    }

    for summary in body_summaries {
        let tolerance_summary = body_tolerance_summary(summary, backend_family);
        accumulators[body_class(&tolerance_summary.body).index()]
            .push_tolerance(&tolerance_summary);
    }

    accumulators
        .into_iter()
        .filter(|summary| summary.body_count > 0)
        .map(BodyClassToleranceAccumulator::finish)
        .collect()
}

/// Returns the expected comparison-tolerance catalog for a backend family.
///
/// The catalog is grouped by body-class scope and keeps the backend family
/// explicit in each tolerance row so validation and release tooling can reuse
/// the same stored thresholds without rebuilding them ad hoc.
pub fn comparison_tolerance_catalog_entries(
    backend_family: &BackendFamily,
) -> Vec<ComparisonToleranceEntry> {
    [
        ComparisonToleranceScope::Luminary,
        ComparisonToleranceScope::MajorPlanet,
        ComparisonToleranceScope::LunarPoint,
        ComparisonToleranceScope::Asteroid,
        ComparisonToleranceScope::Custom,
        ComparisonToleranceScope::Pluto,
    ]
    .into_iter()
    .map(|scope| ComparisonToleranceEntry {
        scope,
        tolerance: comparison_tolerance_for_scope(scope, backend_family),
    })
    .collect()
}

pub(crate) fn comparison_tolerance_policy_entries(
    backend_family: &BackendFamily,
) -> Vec<ComparisonToleranceEntry> {
    comparison_tolerance_catalog_entries(backend_family)
}

fn comparison_tolerance_for_scope(
    scope: ComparisonToleranceScope,
    backend_family: &BackendFamily,
) -> ComparisonTolerance {
    match scope {
        ComparisonToleranceScope::Luminary => ComparisonTolerance {
            backend_family: backend_family.clone(),
            profile: "phase-1 full-file VSOP87B planetary evidence",
            max_longitude_delta_deg: LUMINARY_LONGITUDE_THRESHOLD_DEG,
            max_latitude_delta_deg: LUMINARY_LATITUDE_THRESHOLD_DEG,
            max_distance_delta_au: Some(LUMINARY_DISTANCE_THRESHOLD_AU),
        },
        ComparisonToleranceScope::MajorPlanet => ComparisonTolerance {
            backend_family: backend_family.clone(),
            profile: "phase-1 full-file VSOP87B planetary evidence",
            max_longitude_delta_deg: MAJOR_PLANET_LONGITUDE_THRESHOLD_DEG,
            max_latitude_delta_deg: MAJOR_PLANET_LATITUDE_THRESHOLD_DEG,
            max_distance_delta_au: Some(MAJOR_PLANET_DISTANCE_THRESHOLD_AU),
        },
        ComparisonToleranceScope::LunarPoint => ComparisonTolerance {
            backend_family: backend_family.clone(),
            profile: "phase-1 compact-ELP lunar evidence",
            max_longitude_delta_deg: LUNAR_POINT_LONGITUDE_THRESHOLD_DEG,
            max_latitude_delta_deg: LUNAR_POINT_LATITUDE_THRESHOLD_DEG,
            max_distance_delta_au: Some(LUNAR_POINT_DISTANCE_THRESHOLD_AU),
        },
        ComparisonToleranceScope::Asteroid => ComparisonTolerance {
            backend_family: backend_family.clone(),
            profile: "phase-1 asteroid comparison evidence",
            max_longitude_delta_deg: ASTEROID_LONGITUDE_THRESHOLD_DEG,
            max_latitude_delta_deg: ASTEROID_LATITUDE_THRESHOLD_DEG,
            max_distance_delta_au: Some(ASTEROID_DISTANCE_THRESHOLD_AU),
        },
        ComparisonToleranceScope::Custom => ComparisonTolerance {
            backend_family: backend_family.clone(),
            profile: "phase-1 uncategorized comparison evidence",
            max_longitude_delta_deg: CUSTOM_LONGITUDE_THRESHOLD_DEG,
            max_latitude_delta_deg: CUSTOM_LATITUDE_THRESHOLD_DEG,
            max_distance_delta_au: Some(CUSTOM_DISTANCE_THRESHOLD_AU),
        },
        ComparisonToleranceScope::Pluto => ComparisonTolerance {
            backend_family: backend_family.clone(),
            profile: "phase-1 Pluto approximate fallback evidence",
            max_longitude_delta_deg: PLUTO_LONGITUDE_THRESHOLD_DEG,
            max_latitude_delta_deg: PLUTO_LATITUDE_THRESHOLD_DEG,
            max_distance_delta_au: Some(PLUTO_DISTANCE_THRESHOLD_AU),
        },
    }
}

fn comparison_tolerance_scope_for_class(class: BodyClass) -> ComparisonToleranceScope {
    match class {
        BodyClass::Luminary => ComparisonToleranceScope::Luminary,
        BodyClass::MajorPlanet => ComparisonToleranceScope::MajorPlanet,
        BodyClass::LunarPoint => ComparisonToleranceScope::LunarPoint,
        BodyClass::Asteroid => ComparisonToleranceScope::Asteroid,
        BodyClass::Custom => ComparisonToleranceScope::Custom,
    }
}

pub(crate) fn comparison_tolerance_scope_for_body(
    body: &CelestialBody,
) -> ComparisonToleranceScope {
    if matches!(body, CelestialBody::Pluto) {
        return ComparisonToleranceScope::Pluto;
    }

    comparison_tolerance_scope_for_class(body_class(body))
}

fn comparison_tolerance_for_class(
    class: BodyClass,
    backend_family: &BackendFamily,
) -> ComparisonTolerance {
    comparison_tolerance_for_scope(comparison_tolerance_scope_for_class(class), backend_family)
}

pub(crate) fn comparison_tolerance_for_body(
    body: &CelestialBody,
    backend_family: &BackendFamily,
) -> ComparisonTolerance {
    comparison_tolerance_for_scope(comparison_tolerance_scope_for_body(body), backend_family)
}

fn body_tolerance_summary(
    summary: BodyComparisonSummary,
    backend_family: &BackendFamily,
) -> BodyToleranceSummary {
    let tolerance = comparison_tolerance_for_body(&summary.body, backend_family);
    let distance_within = match (
        summary.max_distance_delta_au,
        tolerance.max_distance_delta_au,
    ) {
        (Some(measured), Some(limit)) => measured <= limit,
        (None, _) | (_, None) => true,
    };
    let within_tolerance = summary.max_longitude_delta_deg <= tolerance.max_longitude_delta_deg
        && summary.max_latitude_delta_deg <= tolerance.max_latitude_delta_deg
        && distance_within;
    let longitude_margin_deg = tolerance.max_longitude_delta_deg - summary.max_longitude_delta_deg;
    let latitude_margin_deg = tolerance.max_latitude_delta_deg - summary.max_latitude_delta_deg;
    let distance_margin_au = match (
        summary.max_distance_delta_au,
        tolerance.max_distance_delta_au,
    ) {
        (Some(measured), Some(limit)) => Some(limit - measured),
        _ => None,
    };

    BodyToleranceSummary {
        body: summary.body,
        tolerance,
        sample_count: summary.sample_count,
        within_tolerance,
        max_longitude_delta_deg: summary.max_longitude_delta_deg,
        longitude_margin_deg,
        max_latitude_delta_deg: summary.max_latitude_delta_deg,
        latitude_margin_deg,
        max_distance_delta_au: summary.max_distance_delta_au,
        distance_margin_au,
    }
}
